### ISSUE TITLE
[ARM][CI] Build fails with timeout

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#10114]
See https://github.com/open-telemetry/opentelemetry-collector/actions/runs/8987902640/job/24690055429?pr=10112

```
2024-05-07T16:20:47.205Z	INFO	builder/main.go:111	Compiling
panic: test timed out after 4m0s
running tests:
	TestVersioning (4m0s)
	TestVersioning/old_component_version (8s)

goroutine 61 [running]:
testing.(*M).startAlarm.func1()
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:2366 +0x1dc
created by time.goFunc
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/time/sleep.go:177 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00016a1a0, {0x5a1d52, 0xe}, 0x5d5f78)
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:1750 +0x604
testing.runTests.func1(0xc00016a1a0)
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:2161 +0x84
testing.tRunner(0xc00016a1a0, 0xc00003d9e8)
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:1689 +0x184
testing.runTests(0xc0001681c8, {0x932400, 0x12, 0x12}, {0xc00003da78?, 0x5c2a4?, 0x938980?})
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:2159 +0x6e4
testing.(*M).Run(0xc000110820)
	/home/runner/actions-runner/_work/_tool/go/1.22.2/arm64/src/testing/testing.go:2027 +0xb78
go.uber.org/goleak.VerifyTestMain({0x665fe0, 0xc000110820}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x48
go.opentelemetry.io/collector/cmd/builder/internal/builder.TestMain(...)
	/home/runner/actions-runner/_work/opentelemetry-collector/opentelemetry-collector/cmd/builder/internal/builder/package_test.go:13
main.main()
	_testmain.go:83 +0x2b4
```

**Comment by mx-psi** [comment]
We can probably change this to `Generate` only for some of the subtests: https://github.com/open-telemetry/opentelemetry-collector/blob/9bc32498ce5edc12222ced1db46378e26dbd3cce/cmd/builder/internal/builder/main_test.go#L180 that would be an easy way to reduce the time this test takes

**Comment by atoulme** [comment]
This is no longer applicable, we moved to github actions runner.
