### ISSUE TITLE
Nil pointer dereference panics with the recordDataPoint call within a goroutine

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/opentelemetry-collector#10330]
**Describe the bug**
When calling `record<mymetric` functions generated by `mdatagen` within a goroutine, there inconsistenltly consistent nil pointer dereference panics. This occurs on the `recordDataPoint` function specifically. The `start pcommon.Timestamp` value passed to `recordDataPoint` is the value that always shows up nil.

**Steps to reproduce**
The fastest way to reproduce this is to run version `v0.55.0` of our distribution of OTEL which is a version prior to me fixing the issue. 

Another means of re-producing this is to create a scraper receiver, add a goroutine, and call the record metric functions multiple times in each goroutine. 

**What did you expect to see?**
I expected it the record statements to work within GoRoutines.

**What did you see instead?**

Below is the error that would consistently show up. Usually around the 24 minute mark. Adding logging statements slowed it down to the point where it wouldn't occur until about 4 hours in.

It's always the [start](https://github.com/liatrio/liatrio-otel-collector/blob/main/receiver/gitproviderreceiver/internal/metadata/generated_metrics.go#L147C72-L157) value which is set when a [newScraper](https://github.com/liatrio/liatrio-otel-collector/blob/main/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go#L47) is created. 

```
collector/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go:140
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x266bb2e]
goroutine 82 [running]:
go.opentelemetry.io/collector/pdata/pmetric.NumberDataPoint.SetStartTimestamp(...)
/home/runner/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.7.0/pmetric/generated_numberdatapoint.go:62
github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata.(*metricGitRepositoryBranchCommitAheadbyCount).recordDataPoint(0x0?, 0x17d61c96aaecb701, 0x17d61c98ff28aab9, 0x1, {0xc0002bd8c0, 0x1d}, {0xc000bdfe00, 0x39})
/home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata/generated_metrics.go:100 +0x16e
github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata.(*MetricsBuilder).RecordGitRepositoryBranchCommitAheadbyCountDataPoint(...)
/home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/metadata/generated_metrics.go:928
github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper.(*githubScraper).scrape.func1()
/home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go:123 +0x56b
created by github.com/liatrio/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper.(*githubScraper).scrape in goroutine 54
/home/runner/work/liatrio-otel-collector/liatrio-otel-collector/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go:102 +0xa46
```

**What version did you use?**
v1.0.0 to v1.7.0 of mdatagen.

**What config did you use?**
Several for the Git Provider Receiver

**Environment**
Darwin Arm64
Linux AMD64
Cloud and local

**Additional context**

I brought this up during the collector meeting. Based on [this information](https://tip.golang.org/doc/comment#type) this may not be a "real" issue as types aren't be default guaranteed to be goroutine safe. 

> By default, programmers should expect that a type is safe for use only by a single goroutine at a time. If a type provides stronger guarantees, the doc comment should state them.

That being said, this was something that appeared to be working at a smaller scale of record statements previously. My thought is that maybe it'd be good to call out specifically that this isn't goroutine safe and a mutex should exist to ensure recording works. My thinking behind calling this out is that this is that mdatagen is essential for building metrics and is widely used, it might help prevent someone else from running into the problem I did. I completely understand if that's not the direction chosen though because of the standard.

**Comment by adrielp** [comment]
I think this issue can be closed based on the information about doc comments that had been provided. The only reason I could think of to leave it open would be if we want to guarantee thread safety on the record metrics type.
