### ISSUE TITLE
Generated NewTelemetryBuilder function panics with no LeveledMeterProvider

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/opentelemetry-collector#11684]
**Describe the bug**
If the `LeveledMeterProvider` is not defined, the `NewTelemetryBuilder` function will panic.

**Steps to reproduce**
I was experimenting with black magic and did this to find the issue:
```go
func main() {
	ctx := context.Background()
	f := transformprocessor.NewFactory()
	c := &inMemoryConsumer{}
	l, err := zap.NewDevelopment()
	if err != nil {
		log.Fatal(err)
	}
	m, err := f.CreateMetrics(
		ctx,
		processor.Settings{
			TelemetrySettings: component.TelemetrySettings{
				Logger: l,
			},
		},
		&transformprocessor.Config{},
		c,
	)
	if err != nil {
		log.Fatal(err)
	}

	m.ConsumeMetrics(ctx, pmetric.NewMetrics())
}
```

**What did you expect to see?**
I expected to see an error telling me what I forgot to specify in the TelemetrySettings.

**What did you see instead?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb7281]

goroutine 1 [running]:
go.opentelemetry.io/collector/processor/processorhelper/internal/metadata.LeveledMeter({0xc00017f800, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}}, 0x0)
        /usr/local/google/home/braydonk/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.113.0/processorhelper/internal/metadata/generated_telemetry.go:21 +0x41
go.opentelemetry.io/collector/processor/processorhelper/internal/metadata.NewTelemetryBuilder({0xc00017f800, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}}, {0x0, ...})
        /usr/local/google/home/braydonk/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.113.0/processorhelper/internal/metadata/generated_telemetry.go:55 +0x1b0
go.opentelemetry.io/collector/processor/processorhelper.newObsReport({{{{0x0, 0x0}}, {0x0, 0x0}}, {0xc00017f800, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
        /usr/local/google/home/braydonk/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.113.0/processorhelper/obsreport.go:26 +0x93
go.opentelemetry.io/collector/processor/processorhelper.NewMetrics({0x0?, 0x0?}, {{{{0x0, 0x0}}, {0x0, 0x0}}, {0xc00017f800, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
        /usr/local/google/home/braydonk/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.113.0/processorhelper/metrics.go:42 +0x98
github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor.createMetricsProcessor({0x12b6580, 0x1c659e0}, {{{{0x0, 0x0}}, {0x0, 0x0}}, {0xc00017f800, {0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
        /usr/local/google/home/braydonk/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor@v0.113.0/factory.go:99 +0x293
go.opentelemetry.io/collector/processor.CreateMetricsFunc.CreateMetrics(...)
        /usr/local/google/home/braydonk/go/pkg/mod/go.opentelemetry.io/collector/processor@v0.113.0/processor.go:144
main.main()
        /usr/local/google/home/braydonk/Git/ottltester/main.go:23 +0xff
exit status 2
```

**What version did you use?**
v0.113.0

**Comment by braydonk** [comment]
I am going to fix this for contribfest!

**Comment by braydonk** [comment]
Made obsolete by https://github.com/open-telemetry/opentelemetry-collector/pull/11415
