### ISSUE TITLE
kafka receiver panic: close of closed channel

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-collector#1692]
**Describe the bug**
I use kafkareceiver to receive data. When running for a period of time (about 10s), the program will panic.

```
panic: close of closed channel

goroutine 201 [running]:
go.opentelemetry.io/collector/receiver/kafkareceiver.(*consumerGroupHandler).Setup(0xc0000ae880, 0x1b8eea0, 0xc000798200, 0xc001d50660, 0xc000798200)
        /Users/niaoge/go/pkg/mod/go.opentelemetry.io/collector@v0.9.1-0.20200831045722-c3f7dd5e40a3/receiver/kafkareceiver/kafka_receiver.go:131 +0x36
github.com/Shopify/sarama.newConsumerGroupSession(0x1b79980, 0xc001544280, 0xc00002a3f0, 0xc001684150, 0xc0000100c0, 0x3b, 0x1c4f, 0x1b74dc0, 0xc0000ae880, 0x0, ...)
        /Users/niaoge/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:597 +0x464
github.com/Shopify/sarama.(*consumerGroup).newSession(0xc00002a3f0, 0x1b79980, 0xc0000ae840, 0xc0001d2610, 0x1, 0x1, 0x1b74dc0, 0xc0000ae880, 0x4, 0xc00004a280, ...)
        /Users/niaoge/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:299 +0x2f7
github.com/Shopify/sarama.(*consumerGroup).Consume(0xc00002a3f0, 0x1b79980, 0xc0000ae840, 0xc0001d2610, 0x1, 0x1, 0x1b74dc0, 0xc0000ae880, 0x0, 0x0)
        /Users/niaoge/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:169 +0x18b
go.opentelemetry.io/collector/receiver/kafkareceiver.(*kafkaConsumer).consumeLoop(0xc0001e0690, 0x1b79980, 0xc0000ae840, 0x1b74dc0, 0xc0000ae880, 0x8c2c25, 0xc000022630)
        /Users/niaoge/go/pkg/mod/go.opentelemetry.io/collector@v0.9.1-0.20200831045722-c3f7dd5e40a3/receiver/kafkareceiver/kafka_receiver.go:103 +0x9b
created by go.opentelemetry.io/collector/receiver/kafkareceiver.(*kafkaConsumer).Start
        /Users/niaoge/go/pkg/mod/go.opentelemetry.io/collector@v0.9.1-0.20200831045722-c3f7dd5e40a3/receiver/kafkareceiver/kafka_receiver.go:93 +0x169
```

**Comment by pavolloffay** [comment]
The seems that the `ConsumerGroupHandler.Setup` was called multiple times  https://github.com/open-telemetry/opentelemetry-collector/blob/7f13eb66c33341f840f83f43a5fc2bf2f9c8628c/receiver/kafkareceiver/kafka_receiver.go#L131 and it tried to close the ready channel twice. 

Our impl is based on their example https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L142. Maybe the setup can be called multiple times - e.g. on rebalance?
