### ISSUE TITLE
Error traces sent to New Relic and Datadog are not being recognized as errors

### ISSUE THREAD

**Issue by stephenhong** [open-telemetry/opentelemetry-collector#2181]
**Describe the bug**
I have a Node.js application sending traces to New Relic and Datadog. I'm using the latest release (0.14.0) of the OpenTelemetry Collector. I generated a 500 error with my app and the trace data was sent to both New Relic and Datadog. In both tools, the trace displayed the stack trace. However, neither tools recognized the trace as an error trace

**Steps to reproduce**
Node.js application using 'signalfx-tracing' sends error traces to the latest release (0.14.0) of the OpenTelemetry Collector. Configure the collector to export traces to New Relic and Datadog.

**What did you expect to see?**
New Relic and Datadog recognizing the error traces as errors

**What did you see instead?**
New Relic and Datadog not recognizing the error traces as errors

**What version did you use?**
Version: v0.14.0

**What config did you use?**
Config: the yaml config file

**Environment**
OS: Amazon EC2 instance
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
I can provide screenshots if needed

**Comment by bogdandrutu** [comment]
Can you install the logging exporter and copy-paste the output for one of the trace?

**Comment by stephenhong** [comment]
2020-11-19T16:45:07.394Z	INFO	loggingexporter/logging_exporter.go:313	TracesExporter	{"#spans": 9}
2020-11-19T16:45:07.394Z	DEBUG	loggingexporter/logging_exporter.go:370	ResourceSpans #0
Resource labels:
     -> service.name: STRING(nodejs-mysql)
InstrumentationLibrarySpans #0
Span #0
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 330fc72c2d59ce8e
    Name           : expressTrace
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.542696 +0000 UTC
    End time       : 2020-11-19 16:45:05.542857 +0000 UTC
Attributes:
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
Span #1
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 38207c99007e4da6
    Name           : expressInit
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.54238 +0000 UTC
    End time       : 2020-11-19 16:45:05.542613 +0000 UTC
Attributes:
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
Span #2
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 5b980014b24f99bf
    Name           : query
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.541863 +0000 UTC
    End time       : 2020-11-19 16:45:05.542232 +0000 UTC
Attributes:
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
     -> component: STRING(express)
Span #3
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 7075e928069fe4b1
    ID             : 4003cf5725119575
    Name           : <anonymous>
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.543749 +0000 UTC
    End time       : 2020-11-19 16:45:05.543956 +0000 UTC
Attributes:
     -> sfx.error.kind: STRING(ReferenceError)
     -> sfx.error.message: STRING(error is not defined)
     -> sfx.error.stack: STRING(ReferenceError: error is not defined
    at Layer.<anonymous> (/root/distributed-tracing-nodejs/server.js:48:9)
    at /root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/plugins/router.js:111:19
    at Scope._activate (/root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/scope/new/scope.js:45:14)
    at Scope.activate (/root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/scope/new/base.js:13:17)
    at Object.wrapMiddleware (/root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/plugins/util/web.js:115:27)
    at callHandle (/root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/plugins/router.js:106:14)
    at /root/distributed-tracing-nodejs/node_modules/signalfx-tracing/src/plugins/router.js:62:14
    at Layer.handle [as handle_request] (/root/distributed-tracing-nodejs/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/distributed-tracing-nodejs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/distributed-tracing-nodejs/node_modules/express/lib/router/route.js:112:3))
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
     -> component: STRING(express)
     -> error: STRING(true)
Span #4
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 0e0bfe3bf70398d8
    Name           : urlencodedParser
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.543148 +0000 UTC
    End time       : 2020-11-19 16:45:05.543236 +0000 UTC
Attributes:
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
Span #5
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 4296f383cc452ff5
    Name           : jsonParser
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.542912 +0000 UTC
    End time       : 2020-11-19 16:45:05.543116 +0000 UTC
Attributes:
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
Span #6
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 
    ID             : 23da87b76f03daba
    Name           : /e
    Kind           : SPAN_KIND_SERVER
    Start time     : 2020-11-19 16:45:05.540629 +0000 UTC
    End time       : 2020-11-19 16:45:05.547325 +0000 UTC
Attributes:
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> http.route: STRING(/e)
     -> http.status_code: STRING(500)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
     -> http.url: STRING(http://10.203.250.241:3030/e)
     -> error: STRING(true)
     -> http.method: STRING(GET)
     -> component: STRING(http)
Span #7
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 23da87b76f03daba
    ID             : 7075e928069fe4b1
    Name           : bound dispatch
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.543629 +0000 UTC
    End time       : 2020-11-19 16:45:05.545747 +0000 UTC
Attributes:
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
     -> environment: STRING(nodejs-mysql)
Span #8
    Trace ID       : 00000000000000002db198d7c8a9da91
    Parent ID      : 7075e928069fe4b1
    ID             : 7c5f4d080123b102
    Name           : <anonymous>
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : 2020-11-19 16:45:05.544032 +0000 UTC
    End time       : 2020-11-19 16:45:05.545738 +0000 UTC
Attributes:
     -> environment: STRING(nodejs-mysql)
     -> component: STRING(express)
     -> signalfx.tracing.library: STRING(nodejs-tracing)
     -> signalfx.tracing.version: STRING(0.7.0)
