### ISSUE TITLE
Test: timeout on jaegerreceiver test

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector#225]
Hit this on #224 
```
panic: test timed out after 30s

goroutine 65 [running]:
testing.(*M).startAlarm.func1()
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:1334 +0x11c
created by time.goFunc
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/time/sleep.go:169 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000c8600, 0x129a079, 0x11, 0x12cae10, 0x1)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:917 +0x693
testing.runTests.func1(0xc0000c8600)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:1157 +0xa9
testing.tRunner(0xc0000c8600, 0xc00027dd48)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:865 +0x164
testing.runTests(0xc00000f700, 0x1bf94e0, 0xe, 0xe, 0x0)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:1155 +0x524
testing.(*M).Run(0xc00010a500, 0x0)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:1072 +0x2ec
main.main()
	_testmain.go:120 +0x335

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000ccf00)
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x1d6
created by go.opencensus.io/stats/view.init.0
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x9a

goroutine 54 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc0003cefc0, 0x141ef00, 0xc0002e9050, 0x573600, 0x12b19cf, 0x29, 0x0, 0xc0003cf150, 0xc0003e97a0, 0x5757ac, ...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/picker_wrapper.go:121 +0xf94
google.golang.org/grpc.(*ClientConn).getTransport(0xc000157880, 0x141ef00, 0xc0002e9050, 0x0, 0x12b19cf, 0x29, 0x120, 0x7f5205d482c8, 0xf8, 0x110, ...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/clientconn.go:839 +0xb2
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0002e4ea0, 0x0, 0x0, 0x0, 0x10fb9e0, 0xc00048c080)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:342 +0x380
google.golang.org/grpc.newClientStream(0x141ef00, 0xc0002e9050, 0x1c06500, 0xc000157880, 0x12b19cf, 0x29, 0xc00048c060, 0x1, 0x1, 0x0, ...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/stream.go:285 +0x1035
google.golang.org/grpc.invoke(0x141ee80, 0xc00003a1c8, 0x12b19cf, 0x29, 0x120eaa0, 0xc0002eaf60, 0x1208480, 0x1c23f58, 0xc000157880, 0xc00048c060, ...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/call.go:66 +0xc8
google.golang.org/grpc.(*ClientConn).Invoke(0xc000157880, 0x141ee80, 0xc00003a1c8, 0x12b19cf, 0x29, 0x120eaa0, 0xc0002eaf60, 0x1208480, 0x1c23f58, 0xc00048c060, ...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/call.go:37 +0x278
google.golang.org/grpc.Invoke(...)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/call.go:60
github.com/jaegertracing/jaeger/proto-gen/api_v2.(*collectorServiceClient).PostSpans(0xc000010788, 0x141ee80, 0xc00003a1c8, 0xc0002eaf60, 0xc00048c060, 0x1, 0x1, 0xc000157880, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/jaegertracing/jaeger@v1.9.0/proto-gen/api_v2/api_v2.pb.go:298 +0x10d
github.com/open-telemetry/opentelemetry-service/receiver/jaegerreceiver.TestGRPCReception(0xc0003dcb00)
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/jaegerreceiver/trace_receiver_test.go:123 +0x7cd
testing.tRunner(0xc0003dcb00, 0x12cae10)
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/testing/testing.go:916 +0x65b

goroutine 55 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0003cf100)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/balancer_conn_wrappers.go:115 +0x204
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/balancer_conn_wrappers.go:106 +0x2ba

goroutine 56 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000136dc0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/clientconn.go:1058 +0x4cf
created by google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.21.0/clientconn.go:767 +0xfc
FAIL	github.com/open-telemetry/opentelemetry-service/receiver/jaegerreceiver	30.052s
```

**Comment by jpkrohling** [comment]
I should probably look into this one. Feel free to assign it to me.

**Comment by jpkrohling** [comment]
@pjanotti how often have you faced this? I can try to set `grpc.WithBlock()` on `grpc.Dial()`, but that probably wouldn't have helped here, as this seems to be a race condition some layers down.

**Comment by tigrannajaryan** [comment]
@jpkrohling assigned to you, thanks.
