### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector#2975]
$ go test ./...

```
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43d55a8]

goroutine 490 [running]:
net/http.(*Server).setupHTTP2_Serve(...)
	/usr/local/go/src/net/http/server.go:3228
net/http.(*Server).Serve(0x0, 0x6ea53d8, 0xc00065cde0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2960 +0x148
go.opentelemetry.io/collector/receiver/jaegerreceiver.(*jReceiver).startCollector.func1(0xc000532000, 0x6ea53d8, 0xc00065cde0)
	/Users/jbd/opentelemetry-collector/receiver/jaegerreceiver/trace_receiver.go:469 +0x45
created by go.opentelemetry.io/collector/receiver/jaegerreceiver.(*jReceiver).startCollector
	/Users/jbd/opentelemetry-collector/receiver/jaegerreceiver/trace_receiver.go:468 +0x714
FAIL	go.opentelemetry.io/collector/service/defaultcomponents	2.698s
```

**Comment by rakyll** [comment]
This is not consistently failing but is a flaky test.
