### ISSUE TITLE
Open-telemetry collector panic crash with Prometheus

### ISSUE THREAD

**Issue by girishgrover2008** [open-telemetry/opentelemetry-collector#3058]
**Describe the bug**
I am using opentelemetry collector to collect data from Prometheus which is monitoring our kubernetes cluster. Idea is open telemetry  collector can collect data from Prometheus and report it to our API. While doing so collector is getting panicked and crashing with segmentation fault.  

**Steps to reproduce**
Attaching yaml file for the config that i am using and monitoring the kubernetes cluster.

**What did you expect to see?**
Our API server is running grpc receiver, open telemetry should have collected metrics and forwarded to the API server.

**What did you see instead?**
Segmentation fault with bunch of errors/warnings.

**What version did you use?**
{"Version": "v0.25.0", "GitHash": "d93c9d29", "NumCPU": 16}

**What config did you use?**
Attached config.
[ot-collector.yaml.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6397686/ot-collector.yaml.txt)

**Environment**
Running above yaml file as a pod on a kubernetes server. 

Logs :
Attached.
[logs.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6397766/logs.txt)

**Comment by rakyll** [comment]
This seems to be affecting the summary types. cc @Aneurysm9 @odeke-em

**Comment by odeke-em** [comment]
Here is the extracted stacktrace
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2643d4c]

goroutine 5548 [running]:
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoint(0xc068d39990, 0x7, 0xc10dd4cc80, 0xc027aea0c0, 0xc027aea0c0, 0xc068d39568)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:339 +0x40c
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoints(0xc068d39990, 0x7, 0xc0b4aea9d8, 0x1, 0x1, 0xc021535ed8, 0x1, 0x1, 0xc021535ed8, 0x1, ...)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:292 +0x465
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustTimeseries(0xc068d39990, 0xc000000007, 0xc0b5556000, 0xc027ab3ce0, 0xc027ab3ce0, 0xc027b20000)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:277 +0xbb
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetricTimeseries(0xc068d39990, 0xc04d5d7540, 0xc0320d3301, 0x0)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:257 +0x1e5
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetric(0xc068d39990, 0xc04d5d7540, 0x1, 0x0)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:239 +0x5c
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).AdjustMetrics(0xc068d39990, 0xc09f3d4e00, 0x33, 0x40, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:214 +0x149
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc057b791e0, 0xc01abc2a495faa21, 0x116035ba7e)
        /home/circleci/project/receiver/prometheusreceiver/internal/transaction.go:175 +0x4a5
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc068d39c18, 0xc068d39c28, 0xc0097c7ef0)
        /home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1086 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc0097c7ef0, 0xdf8475800, 0x2540be400, 0xc01abc1b495fb896, 0x367ee70dc, 0x47d96e0, 0xc01abc2a495faa21, 0x116035ba7e, 0x47d96e0, 0x0, ...)
        /home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1153 +0xb45
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0097c7ef0, 0xdf8475800, 0x2540be400, 0x0)
        /home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1039 +0x39e
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
        /home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:510 +0x9ce
```

**Comment by girishgrover2008** [comment]
@odeke-em its happening continuously. I will try the collector that you have suggested and get back to you.

**Comment by ipstatic** [comment]
@odeke-em I am experiencing a similar issue (constant crashing) and tried the above commit to no avail. Is there another commit that would be a good place to test? For reference the stacktrace looks like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x27c009a]
goroutine 705 [running]:
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).isReset(0xc006619ae8, 0xc000000007, 0xc007ba7d00, 0xc00438d8c0, 0x0)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:296 +0x1da
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoints(0xc006619ae8, 0x7, 0xc00774d1e0, 0x1, 0x1, 0xc00400e6d8, 0x1, 0x1, 0xc00400e6d8, 0x1, ...)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:274 +0x3f9
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustTimeseries(0xc006619ae8, 0xc000000007, 0xc007b7f860, 0xc0042ecb40, 0xc0042ecb40, 0xc004d669f0)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:259 +0xbb
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetricTimeseries(0xc006619ae8, 0xc00b49c960, 0x41)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:243 +0x289
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetric(...)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:233
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).AdjustMetrics(0xc006619ae8, 0xc0067ac800, 0x41, 0x80, 0x0, 0x0, 0x0, 0x0)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/metrics_adjuster.go:212 +0x1f8
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc009cdb260, 0x21b923c2, 0xed85d65d4)
        go.opentelemetry.io/collector@v0.28.0/receiver/prometheusreceiver/internal/transaction.go:197 +0x406
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc006619ce8, 0xc006619cf8, 0xc0000106e0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1096 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc0000106e0, 0x37e11d600, 0x2540be400, 0x0, 0x0, 0x0, 0x21b923c2, 0xed85d65d4, 0x611a2e0, 0x0, ...)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1163 +0xb4d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0000106e0, 0x37e11d600, 0x2540be400, 0x0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1049 +0x365
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:518 +0x9ce
```

cc: @dashpole

**Comment by Aneurysm9** [comment]
I think this is related to [this mistaken bounds check](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/prometheusreceiver/internal/metrics_adjuster.go#L269):

```go
	if len(current) != 1 || len(initial) != 1 || len(current) != 1 {
```

That should be:

```go
	if len(current) != 1 || len(initial) != 1 || len(previous) != 1 {
```

**Comment by Aneurysm9** [comment]
@ipstatic if you're able to reliably reproduce this can you try a build from the branch on #3486?

**Comment by ipstatic** [comment]
@Aneurysm9 I am able to reliably reproduce and I do not see this issue on your branch.

**Comment by ipstatic** [comment]
It appears the PR associated with this issue has been merged but is not in the latest Beta (0.30.0). How can we ensure it gets in the next release?
