### ISSUE TITLE
Async nature of collector startup makes it hard to sync telemetry init failures with start of sending e.g. heartbeats 

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector#3778]
**Describe the bug**

Having a plugin e.g. extension that starts sending data e.g. heartbeats upon startup it's hard to synchronize it with telemetry init failures coming from e.g. binding the prometheus exporter on an already used port (ref: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.31.0/service/telemetry.go#L114-L119 )

This causes a collector to send data/heartbeats/healthecks/(?) and then get asynchronously terminated because of:

```
listen tcp :8888: bind: address already in use
```

which yields incorrect collector from a remote API/backend perspective.

**Steps to reproduce**

* start a processor
* start a second processor using the same `metrics-addr` command line param
* observe: 

```
2021-08-05T16:07:54.165+0200    error   service/collector.go:223        Asynchronous error received, terminating process        {"error": "listen tcp :8888: bind: address already in use"}
go.opentelemetry.io/collector/service.(*Collector).runAndWaitForShutdownEvent
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:223
go.opentelemetry.io/collector/service.(*Collector).execute
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:325
go.opentelemetry.io/collector/service.New.func1
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:130
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
go.opentelemetry.io/collector/service.(*Collector).Run
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:167
```

**What version did you use?**

Version: `v0.31.0`

**Environment**

OS: Mac OS
Compiler: "go 1.17.0-rc2"

**Additional context**

Maybe there exists a mechanism on which starting up extensions/plugins/receivers etc can listen on in order to synchronize the startup to prevent sending data from a "half healthy" collector?

Or perhaps there's a chance to contribute such a mechanism?

**Comment by pmalek-sumo** [comment]
I was thinking about swapping 

```
	err := col.setupConfigurationComponents(ctx)
	if err != nil {
		return err
	}

	// Get ballastSizeBytes if ballast extension is enabled
	ballastSizeBytes := col.getBallastSize()
```

with

```
	// Setup Telemetry.
	err = col.setupTelemetry(ballastSizeBytes)
	if err != nil {
		return err
	}
```

in https://github.com/open-telemetry/opentelemetry-collector/blob/967071c7f09dca4a8e08a5df5f4044c67b66775d/service/collector.go#L310-L322 but because of recent changes in how we specify balast this is not possible because balast size is obtained from an extension and that needs to be initialized with `col.setupConfigurationComponents(ctx)`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x7325c5c]

goroutine 1 [running]:
go.opentelemetry.io/collector/service.(*service).GetExtensions(...)
        go.opentelemetry.io/collector@v0.31.0/service/service.go:126
go.opentelemetry.io/collector/service.(*Collector).getBallastSize(0xc000fb1b38)
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:383 +0x1c
go.opentelemetry.io/collector/service.(*Collector).execute(0xc0009c6580, {0x8d5fcc0, 0xc00019a000})
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:311 +0x2c5
go.opentelemetry.io/collector/service.New.func1(0xc000524f00, {0x84435b4, 0x4, 0x4})
        go.opentelemetry.io/collector@v0.31.0/service/collector.go:130 +0x225
github.com/spf13/cobra.(*Command).execute(0xc000524f00, {0xc0001b4010, 0x4, 0x4})
```
