### ISSUE TITLE
master is broken due to flaky test

### ISSUE THREAD

**Issue by pedro-ribeiro** [open-telemetry/opentelemetry-collector#387]
`TestExportProtocolViolations_nodelessFirstMessage` can fail due to `Log` being called after test has ended.

build log:
```
==================
WARNING: DATA RACE
Read at 0x00c0000f8243 by goroutine 38:
  testing.(*common).logDepth()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:629 +0x132
  testing.(*common).Log()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:614 +0x78
  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x202
Previous write at 0x00c0000f8243 by main goroutine:
  testing.tRunner.func1()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:856 +0x354
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:869 +0x17f
  testing.runTests()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:98 +0x334
Goroutine 38 (running) created at:
  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fa
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:865 +0x163
==================
panic: Log in goroutine after TestExportProtocolViolations_nodelessFirstMessage has completed
goroutine 39 [running]:
testing.(*common).logDepth(0xc0002bc400, 0xc0002acae0, 0x18, 0x3)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:614
testing.(*common).Log(0xc0002bc400, 0xc000053f50, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.10.linux.amd64/src/testing/testing.go:642 +0x79
github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1(0xc00039c000, 0xc0002bc400, 0x77359400, 0xc0002b0fe0)
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x203
created by github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fb
FAIL	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics	0.189s
```

**Comment by pjanotti** [comment]
Closed via #388
