### ISSUE TITLE
BUG: Data race in ocmetrics.TestExportProtocolViolations_nodelessFirstMessage

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#41]
Test randomly failed when building on Travis CI: https://travis-ci.org/open-telemetry/opentelemetry-service/builds/548680880?utm_source=github_status&utm_medium=notification

```
==================
WARNING: DATA RACE
Read at 0x00c0000ac143 by goroutine 36:
  testing.(*common).logDepth()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:629 +0x132
  testing.(*common).Log()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:614 +0x78
  github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x202
Previous write at 0x00c0000ac143 by main goroutine:
  testing.tRunner.func1()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:856 +0x354
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:869 +0x17f
  testing.runTests()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:98 +0x334
Goroutine 36 (running) created at:
  github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fa
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:865 +0x163
==================
panic: Log in goroutine after TestExportProtocolViolations_nodelessFirstMessage has completed
goroutine 51 [running]:
testing.(*common).logDepth(0xc00028a200, 0xc0000270e0, 0x18, 0x3)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:614
testing.(*common).Log(0xc00028a200, 0xc000055750, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:642 +0x79
github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage.func1(0xc00002c230, 0xc00028a200, 0x77359400, 0xc0002f5a20)
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:194 +0x203
created by github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics.TestExportProtocolViolations_nodelessFirstMessage
	/home/travis/gopath/src/github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics/opencensus_test.go:189 +0x3fb
FAIL	github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/ocmetrics	0.201s
ok  	github.com/open-telemetry/opentelemetry-service/receiver/opencensusreceiver/octrace	1.453s	coverage: 75.9% of statements
ok  	github.com/open-telemetry/opentelemetry-service/receiver/prometheusreceiver	6.282s	coverage: 79.4% of statements
?   	github.com/open-telemetry/opentelemetry-service/receiver/vmmetricsreceiver	[no test files]
ok  	github.com/open-telemetry/opentelemetry-service/receiver/zipkinreceiver	1.253s	coverage: 57.4% of statements
ok  	github.com/open-telemetry/opentelemetry-service/receiver/zipkinreceiver/zipkinscribereceiver	1.030s	coverage: 90.6% of statements
ok  	github.com/open-telemetry/opentelemetry-service/translator/trace	1.016s	coverage: 100.0% of statements
ok  	github.com/open-telemetry/opentelemetry-service/translator/trace/jaeger	1.073s	coverage: 85.4% of statements
ok  	github.com/open-telemetry/opentelemetry-service/translator/trace/spandata	1.034s	coverage: 65.0% of statements
ok  	github.com/open-telemetry/opentelemetry-service/translator/trace/zipkin	1.038s	coverage: 88.0% of statements
make: *** [test-with-cover] Error 1
The command "make travis-ci" exited with 2.
```

**Comment by tigrannajaryan** [comment]
Happend again: https://travis-ci.org/open-telemetry/opentelemetry-service/builds/550328623?utm_source=github_status&utm_medium=notification

**Comment by tigrannajaryan** [comment]
Failed again: https://travis-ci.org/open-telemetry/opentelemetry-service/builds/554064637?utm_source=github_status&utm_medium=notification

**Comment by huikang** [comment]
looks like it failed again: https://travis-ci.org/open-telemetry/opentelemetry-collector/builds/622115361#L298

```
```
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics	1.193s	coverage: 84.9% of statements
298==================
299WARNING: DATA RACE
300Read at 0x00c0002e8d43 by goroutine 99:
301  testing.(*common).logDepth()
302      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:621 +0x94
303  testing.(*common).Log()
304      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:614 +0x78
305  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace.TestExportProtocolViolations_nodelessFirstMessage.func1()
306      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace/opencensus_test.go:319 +0x202
307
308Previous write at 0x00c0002e8d43 by goroutine 82:
309  testing.tRunner.func1()
310      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:856 +0x354
311  testing.tRunner()
312      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:869 +0x17f
313
314Goroutine 99 (running) created at:
315  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace.TestExportProtocolViolations_nodelessFirstMessage()
316      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace/opencensus_test.go:314 +0x3c0
317  testing.tRunner()
318      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:865 +0x163
319
320Goroutine 82 (running) created at:
321  testing.(*T).Run()
322      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:916 +0x65a
323  testing.runTests.func1()
324      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1157 +0xa8
325  testing.tRunner()
326      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:865 +0x163
327  testing.runTests()
328      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1155 +0x523
329  testing.(*M).Run()
330      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1072 +0x2eb
331  main.main()
332      _testmain.go:106 +0x334
333==================
```
```

**Comment by pjanotti** [comment]
Another instance. Test failed on #454 

```terminal
==================
WARNING: DATA RACE
Read at 0x00c000113a43 by goroutine 99:
  testing.(*common).logDepth()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:621 +0x94
  testing.(*common).Log()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:614 +0x78
  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace.TestExportProtocolViolations_nodelessFirstMessage.func1()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace/opencensus_test.go:319 +0x202
Previous write at 0x00c000113a43 by goroutine 82:
  testing.tRunner.func1()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:856 +0x354
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:869 +0x17f
Goroutine 99 (running) created at:
  github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace.TestExportProtocolViolations_nodelessFirstMessage()
      /home/travis/gopath/src/github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace/opencensus_test.go:314 +0x3c0
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:865 +0x163
Goroutine 82 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:865 +0x163
  testing.runTests()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.12.14.linux.amd64/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:54 +0x222
==================
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace	0.443s
```

**Comment by tigrannajaryan** [comment]
And again https://circleci.com/gh/open-telemetry/opentelemetry-collector/599

**Comment by pjanotti** [comment]
Looking...
