### ISSUE TITLE
Persistent Queue issues/questions

### ISSUE THREAD

**Issue by ZachTB123** [open-telemetry/opentelemetry-collector#5894]
I'm in the process of evaluating the persistent queueing functionality. I'm using the v0.57.2 release. I am unable to get persistent queuing to work when using multiple replicas of the collector. I currently have two different environments I'm testing this out in and I cannot get either to work. Both of these environments are expected to handle a large volume of telemetry so we have autoscaling set up.

Our first environment is using K8s. We are using the [OpenTelemetry Helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector) and have autoscaling enabled. I created a PVC with the `ReadWriteMany` access mode and mounted it using `extraVolumeMounts`. `persistent_storage_enabled` is set to `true` and the `directory` used by the `file_storage` extension matches the mounted volume path. When the number of replicas is increased, the new replicas that were spun up fail to start due to a timeout which I assume is because it cannot get a lock on the file. Here is a snippet from the logs:

```
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1] Channel switches to new LB policy "pick_first"	{"grpc_log": true}
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1 SubChannel #2] Subchannel created	{"grpc_log": true}
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING	{"grpc_log": true}
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1 SubChannel #2] Subchannel picks a new address "redacted:4317" to connect	{"grpc_log": true}
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] pickfirstBalancer: UpdateSubConnState: 0xc0008c4770, {CONNECTING <nil>}	{"grpc_log": true}
2022-08-10T18:54:47.655Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1] Channel Connectivity change to CONNECTING	{"grpc_log": true}
2022-08-10T18:54:47.836Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1 SubChannel #2] Subchannel Connectivity change to READY	{"grpc_log": true}
2022-08-10T18:54:47.837Z	info	zapgrpc/zapgrpc.go:174	[core] pickfirstBalancer: UpdateSubConnState: 0xc0008c4770, {READY <nil>}	{"grpc_log": true}
2022-08-10T18:54:47.837Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1] Channel Connectivity change to READY	{"grpc_log": true}
Error: cannot start pipelines: timeout
2022/08/10 18:54:48 collector server run finished with error: cannot start pipelines: timeout
```

Our other environment uses [Azure Container Apps](https://azure.microsoft.com/en-us/services/container-apps/#overview). I mounted a file share from Azure Files using [this](https://docs.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=aca-cli#azure-files) approach. As soon as I scale up to multiple replicas, all replicas stop working and constantly restart. I see messages like the following:

```
"2022-08-10T18:49:44.433Z	info	service/telemetry.go:103	Setting up own telemetry..."
"created by go.etcd.io/bbolt.(*DB).freepages"
"2022-08-10T18:49:44.475Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""file_storage""}"
"go.etcd.io/bbolt.(*DB).freepages.func2()"
"2022-08-10T18:49:44.475Z	info	extensions/extensions.go:45	Extension is starting...	{""kind"": ""extension"", ""name"": ""health_check""}"
"panic: freepages: failed to get all reachable pages (page 5: multiple references)"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6"
"2022-08-10T18:49:44.475Z	info	healthcheckextension@v0.57.2/healthcheckextension.go:44	Starting health_check extension	{""kind"": ""extension"", ""name"": ""health_check"", ""config"": {""Endpoint"":""0.0.0.0:13133"",""TLSSetting"":null,""CORS"":null,""Auth"":null,""MaxRequestBodySize"":0,""IncludeMetadata"":false,""Path"":""/"",""CheckCollectorPipeline"":{""Enabled"":false,""Interval"":""5m"",""ExporterFailureThreshold"":5}}}"
"2022-08-10T18:49:44.433Z	info	service/telemetry.go:138	Serving Prometheus metrics	{""address"": ""0.0.0.0:8888"", ""level"": ""detailed""}"
"2022-08-10T18:49:44.475Z	info	extensions/extensions.go:45	Extension is starting...	{""kind"": ""extension"", ""name"": ""oauth2client""}"
"goroutine 96 [running]:"
"2022-08-10T18:49:44.475Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""oauth2client""}"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:45	Extension is starting...	{""kind"": ""extension"", ""name"": ""file_storage""}"
"2022-08-10T18:44:32.663Z	info	healthcheckextension@v0.57.2/healthcheckextension.go:44	Starting health_check extension	{""kind"": ""extension"", ""name"": ""health_check"", ""config"": {""Endpoint"":""0.0.0.0:13133"",""TLSSetting"":null,""CORS"":null,""Auth"":null,""MaxRequestBodySize"":0,""IncludeMetadata"":false,""Path"":""/"",""CheckCollectorPipeline"":{""Enabled"":false,""Interval"":""5m"",""ExporterFailureThreshold"":5}}}"
"panic: freepages: failed to get all reachable pages (page 5: multiple references)"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""health_check""}"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:45	Extension is starting...	{""kind"": ""extension"", ""name"": ""oauth2client""}"
"2022-08-10T18:44:32.629Z	info	service/telemetry.go:138	Serving Prometheus metrics	{""address"": ""0.0.0.0:8888"", ""level"": ""detailed""}"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6"

"2022-08-10T18:44:32.663Z	info	pipelines/pipelines.go:78	Exporter is starting...	{""kind"": ""exporter"", ""data_type"": ""logs"", ""name"": ""otlp/hcp""}"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""oauth2client""}"
"goroutine 135 [running]:"
"2022-08-10T18:44:32.629Z	info	service/telemetry.go:103	Setting up own telemetry..."
"created by go.etcd.io/bbolt.(*DB).freepages"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:45	Extension is starting...	{""kind"": ""extension"", ""name"": ""health_check""}"
"2022-08-10T18:44:32.663Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""file_storage""}"
"2022-08-10T18:44:32.662Z	info	extensions/extensions.go:42	Starting extensions..."
"2022-08-10T18:44:32.663Z	info	pipelines/pipelines.go:74	Starting exporters..."
"go.etcd.io/bbolt.(*DB).freepages.func2()"
"goroutine 131 [running]:"
"created by go.etcd.io/bbolt.(*DB).freepages"
"go.etcd.io/bbolt.(*DB).freepages.func2()"
```

or 

```
"2022-08-09T17:30:24.887Z	info	pipelines/pipelines.go:78	Exporter is starting...	{""kind"": ""exporter"", ""data_type"": ""logs"", ""name"": ""otlp/hcp""}"
"main.runInteractive({{0xc000358ba0, 0xc000358d50, 0xc000358c30, 0xc000358b10}, {{0x31365ba, 0x1d}, {0x3165761, 0x2b}, {0x30fa8ac, 0x5}}, ...})"
go.etcd.io/bbolt.(*Tx).Commit(0xc00016ce00)
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003acc80)
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/internal/persistent_storage.go:247 +0x394"
"go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*persistentContiguousStorage).enqueueNotDispatchedReqs(0xc000b641e0, {0xc0003b4300, 0x30, 0xc000f0f248})"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:537 +0xea"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5"
"github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000f0efa8, {0xc00071ab30, 0x40aa25}, {0xc000907100, 0xc0007d9b60, 0x0})"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/service/collector.go:200 +0x1e9"
panic: page 32 already freed
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/internal/persistent_storage.go:133 +0x288"
"go.opentelemetry.io/collector/component.StartFunc.Start(0xc000f0f470, {0x36ecec8, 0xc000128000}, {0x36ee198, 0xc0009182e8})"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/service/service.go:115 +0xa6"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x32f"
"go.opentelemetry.io/collector/service.NewCommand.func1(0xc0003acc80, {0x30ff580, 0x2, 0x2})"
"github.com/spf13/cobra.(*Command).execute(0xc0003acc80, {0xc000122160, 0x2, 0x2})"
"	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.57.2/filestorage/client.go:143 +0xc5"
"go.etcd.io/bbolt.(*freelist).free(0xc00067c300, 0x21e5ec9, 0x7ff69aaca000)"
"go.opentelemetry.io/collector/service.(*Collector).Run(0xc000f0fb00, {0x36ecec8, 0xc000128000})"
"	/tmp/build/main.go:32 +0x5d"
"2022-08-09T17:30:24.913Z	info	internal/persistent_storage.go:315	Fetching items left for dispatch by consumers	{""kind"": ""exporter"", ""data_type"": ""logs"", ""name"": ""otlp/hcp"", ""queueName"": ""otlp/hcp-logs"", ""numberOfItems"": 48}"
goroutine 1 [running]:
github.com/spf13/cobra.(*Command).Execute(...)

main.run(...)
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*batchStruct).execute(...)
"2022-08-09T17:30:24.886Z	info	extensions/extensions.go:42	Starting extensions..."
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/internal/persistent_storage_batch.go:53"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/queued_retry_experimental.go:162 +0xcf"
main.main()
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/service/internal/pipelines/pipelines.go:79 +0x752"
"	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918"
"	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bc"
"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewPersistentQueue({0x36ecec8, 0xc000128000}, {0xc00071b2f8, 0x8}, {0x30fa2fa, 0x4}, 0xc000763e4d, 0xc000369800, {0x370c618, 0xc00090f770}, ...)"
go.etcd.io/bbolt.(*node).spill(0xc0007364d0)
"go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*persistentContiguousStorage).put(0xc000b641e0, {0x7ff69af542d0, 0xc0007d9b60})"
"2022-08-09T17:30:24.887Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""health_check""}"
"2022-08-09T17:30:24.886Z	info	extensions/extensions.go:49	Extension started.	{""kind"": ""extension"", ""name"": ""oauth2client""}"
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa"
"go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).StartAll(0xc00090f450, {0x36ecec8, 0xc000128000}, {0x36ee160, 0xc000736620})"
"go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start(0xc000838900, {0x36ecec8, 0xc000128000}, {0x36ee198, 0xc0009182e8})"
"2022-08-09T17:30:24.913Z	warn	internal/persistent_storage.go:350	Failed unmarshalling item	{""kind"": ""exporter"", ""data_type"": ""logs"", ""name"": ""otlp/hcp"", ""queueName"": ""otlp/hcp-logs"", ""key"": ""7108903"", ""error"": ""value not set""}"
"2022-08-09T17:30:24.856Z	info	service/telemetry.go:103	Setting up own telemetry..."
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/internal/persistent_queue.go:52 +0x13a"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/common.go:193 +0xae"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/exporter/exporterhelper/queued_retry_experimental.go:198 +0x45"
"	/tmp/build/main.go:25 +0x1d8"
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/component/component.go:82 +0x43"
go.etcd.io/bbolt.(*node).spill(0xc0007363f0)
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216"
go.etcd.io/bbolt.(*Bucket).spill(0xc00016ce18)
"	/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7"
go.etcd.io/bbolt.(*Bucket).spill(0xc0004a6cc0)
"	/go/pkg/mod/go.opentelemetry.io/collector@v0.57.2/service/command.go:50 +0x499"
"go.etcd.io/bbolt.(*DB).Update(0xc000076400, 0xc000f0eee0)"
"go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).initializePersistentQueue(0xc000838900, {0x36ecec8, 0xc000128000}, {0x36ee198, 0xc0009182e8})"
"go.opentelemetry.io/collector/exporter/exporterhelper.newBaseExporter.func1({0x36ecec8, 0xc000128000}, {0x36ee198, 0xc0009182e8})"
```

My question is: is persistent queuing supposed to work with a collector with multiple replicas?

**Comment by pmm-sumo** [comment]
File storage client is using bbolt underneath. One of the limitations is that the same database [cannot be used by multiple processes](https://github.com/etcd-io/bbolt#opening-a-database).

The solution would be to configure the replicas in a way that uses separate path for each of them or to use another type of storage extension, which should be possible after the [recent updates](https://github.com/open-telemetry/opentelemetry-collector/pull/5828) made by @swiatekm-sumo. I haven't tested it with [dbstorage](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/dbstorage) but it could work (though performance impact will might be prohibitive). @swiatekm-sumo what do you think?

**Comment by swiatekm-sumo** [comment]
I don't think this is really bbolt's fault - we get a nice error because it doesn't allow concurrent access, but if it did, the collectors would clobber each others' data. Extensions give components storage clients based on those components' identity, which is what allows the data to persist over restarts, but the identity of the collector itself doesn't really enter into it, and if it did, we'd need to be very careful about determining it.

I think it's reasonable to expect that multiple storage extensions (be it from the same collector instance or from different ones) should have separate storage directories. We should document this better and try to have better error handling for it, though. 

This makes @ZachTB123's use case awkward, and would require parametrising the storage locations with something like the Pod name, injected via the Downwards API. To be completely honest, doing it this way in Kubernetes feels like an antipattern - if you want persistent storage for a Deployment, you should just use a StatefulSet, and have a separate Volume for each Pod.

**Comment by ZachTB123** [comment]
My concern with tying replicas to specific volumes (whether through paths or using StatefulSet) is making sure there is a way to ensure the persistent queue is completely drained before scaling down. For example, if there was an extended outage on the destination we are trying to export to, the replica's volume will start to fill up. Once the export destination is available again, that data in the persistent queue should start to drain. If the number of replicas were to decrease during this time (through auto scaling for example), I would like there to be some guarantee that the data in the volume used by that replica be completely emptied before being shut down. I don't want to encounter a situation where the data would still be in that volume and we would have to wait until the next time that replica comes up to drain the queue. In my situation I need to guarantee timely delivery of the data and I can make no guarantees on the number of replicas for our collector (besides having one replica minimum). This was where I was hoping we could just have one volume shared by all replicas to ensure the queue is drained no matter which replicas come and go from autoscaling.

**Comment by swiatekm-sumo** [comment]
> My concern with tying replicas to specific volumes (whether through paths or using StatefulSet) is making sure there is a way to ensure the persistent queue is completely drained before scaling down. For example, if there was an extended outage on the destination we are trying to export to, the replica's volume will start to fill up. Once the export destination is available again, that data in the persistent queue should start to drain. If the number of replicas were to decrease during this time (through auto scaling for example), I would like there to be some guarantee that the data in the volume used by that replica be completely emptied before being shut down. I don't want to encounter a situation where the data would still be in that volume and we would have to wait until the next time that replica comes up to drain the queue. In my situation I need to guarantee timely delivery of the data and I can make no guarantees on the number of replicas for our collector (besides having one replica minimum). This was where I was hoping we could just have one volume shared by all replicas to ensure the queue is drained no matter which replicas come and go from autoscaling.

Currently, the queue assumes it's the sole consumer of the storage it's using. Even if we were to implement a storage extension allowing concurrent access from different processes (for example a Redis client), I don't think the current storage API is expressive enough to implement a queue like that. In principle, I think it'd be possible with a completely separate queue implementation, without using the storage at all.

I'm aware of the scaling problem, but it hasn't been an issue for us in nearly half a year of using OT to monitor our prod infrastructure. In practice, if you're burning down the queue, your instances should have high resource consumption (as long as you're not I/O bound on the exporter) and an autoscaler shouldn't scale them down.

If you actually want to pursue the idea of a queue sharable by multiple collector processes, we should open a new issue for it, I think.

**Comment by ZachTB123** [comment]
I created #5902 for my previously mentioned concerns around draining the persistent queue.

**Comment by dosmanak** [comment]
Hello. I found the persistent sending queue is in alpha state for 2 years already. Is there a reason not to move it to beta?

**Comment by NapalmCodes** [comment]
This is a real problem in my opinion. Azure Container Apps is a serverless platform. Even if I created a unique name per storage location there is risk the pod (collector) could be scaled down after a long outage. Also new pods will never pick up that location to process (given the unique directory name) leaving the data orphaned.

For what it is worth, Azure Container Apps uses KEDA under the covers and does not give us control beyond a cool down period for scale in actions. My thought is if an extended outage happens, and people stop using the service, then collectors have limited activity.

This greatly limits horizontal scalability of the collector.

**Comment by swiatekm** [comment]
The solution to this problem (of needing a persistent queue shared among multiple collectors) is to export to an external service with the required semantics (in this case, Kafka, Redis, RabbitMQ, etc) and read from that service in a separate layer of collectors, which synchronously export to the actual remotes you want your data in. I'm not convinced such a queue could be implemented in the collector without reproducing a lot of the complexity of, say, kafka, but I'm willing to be proven wrong. If anyone wants to take a stab at it, I suspect it would need to start with an RFC to scope the features and implementation.

**Comment by NapalmCodes** [comment]
Not sure I follow this. I know we can export data to these sources but the receivers seem to be gathering telemetry for Kafka for instance? Are you advocating we have to write a bridge to read the queue and push those into an OTEL collector manually?

**Comment by swiatekm** [comment]
> Not sure I follow this. I know we can export data to these sources but the receivers seem to be gathering telemetry for Kafka for instance? Are you advocating we have to write a bridge to read the queue and push those into an OTEL collector manually?

The [kafkaexporter ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter) can export telemetry to Kafka and the [kafkareceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver) can read it from the other side. It can be a bit confusing, since for these kinds of systems contrib often has two types of receivers - one for collecting the system's own telemetry, and one for collecting data stored in it.
 
> Also seems very heavy handed the solution is to spin up an enterprise queuing system. Just my perspective.

It's not an easy problem to solve. Is there any other telemetry agent that does what you need? Maybe we could take inspiration from that solution.

**Comment by paulo** [comment]
I think I'm seeing the same issue here. I have a single replica deployment in k8s, but the deployment strategy is RollingUpdate, which means that at a certain point 2 separate pods will be up. When this happens with the persistent queue enabled, I'm seeing the following stack:

```
error	graph/graph.go:439	Failed to start component	{"resource": {"service.instance.id": "92245540-fc4b-48e7-acfa-27d439c8c8b4", "service.name": "otelcol-contrib", "service.version": "0.137.0"}, "error": "timeout", "type": "Exporter", "id": "kafka"}

panic: close of closed channel
goroutine 1 [running]:
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*partitionBatcher).Shutdown(0xc001164bd0, {0xd5418c0?, 0x14c0e040?})
	go.opentelemetry.io/collector/exporter/exporterhelper@v0.137.0/internal/queuebatch/partition_batcher.go:218 +0x1c
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*QueueBatch).Shutdown(0xc001a515a0, {0xd5418c0, 0x14c0e040})
	go.opentelemetry.io/collector/exporter/exporterhelper@v0.137.0/internal/queuebatch/queue_batch.go:100 +0x72
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Shutdown(0xc001a2e488, {0xd5418c0, 0x14c0e040})
	go.opentelemetry.io/collector/exporter/exporterhelper@v0.137.0/internal/base_exporter.go:144 +0x89
go.opentelemetry.io/collector/service/internal/graph.(*Graph).ShutdownAll(0xc001132fc0, {0xd5418c0, 0x14c0e040}, {0xd4b7af0, 0xc0000b3b40})
	go.opentelemetry.io/collector/service@v0.137.0/internal/graph/graph.go:478 +0x14e
go.opentelemetry.io/collector/service.(*Service).Shutdown(0xc001859800, {0xd5418c0, 0x14c0e040})
	go.opentelemetry.io/collector/service@v0.137.0/service.go:265 +0xdd
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc0012fea80, {0xd5418c0, 0x14c0e040})
	go.opentelemetry.io/collector/otelcol@v0.137.0/collector.go:241 +0xbce
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0012fea80, {0xd5418c0, 0x14c0e040})
	go.opentelemetry.io/collector/otelcol@v0.137.0/collector.go:310 +0x55
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc001303808, {0xc169630?, 0x7?, 0xc15d1ec?})
	go.opentelemetry.io/collector/otelcol@v0.137.0/command.go:39 +0x94
github.com/spf13/cobra.(*Command).execute(0xc001303808, {0xc0001a42b0, 0x1, 0x1})
	github.com/spf13/cobra@v1.10.1/command.go:1015 +0xb02
github.com/spf13/cobra.(*Command).ExecuteC(0xc001303808)
	github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(0xc5f59f0?)
	github.com/spf13/cobra@v1.10.1/command.go:1071 +0x13
main.runInteractive({0xc5f59f0, {{0xc1aefa0, 0xf}, {0xc28aa23, 0x1f}, {0xc169462, 0x7}, {}}, 0x0, {{{0x0, ...}, ...}, ...}, ...})
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:70 +0x4a
main.run(...)
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:10
main.main()
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:63 +0x598
```

I understand multiple replicas sharing a persistent queue is a difficult problem, but feels like at least this case should be supported (maybe through a "lock file" on disk that the new pod checks before using the underlying queue).
