### ISSUE TITLE
TestResourceMetricsSlice fails sporadically

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#699]
The test is unstable and sometimes fails. Full output:

```
/usr/bin/make -f /Users/tnajaryan/work/repos/opentelemetry-collector/Makefile
go: downloading github.com/open-telemetry/opentelemetry-proto v0.3.0
go: downloading golang.org/x/sys v0.0.0-20191120155948-bd437916bb0e
go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
Check License finished successfully
Static check finished successfully
golangci-lint run
misspell -error ./CONTRIBUTING.md ./README.md ./bin/darwin/config.yaml ./config/testdata/duplicate-exporter.yaml ./config/testdata/duplicate-extension.yaml ./config/testdata/duplicate-pipeline.yaml ./config/testdata/duplicate-processor.yaml ./config/testdata/duplicate-receiver.yaml ./config/testdata/empty-config.yaml ./config/testdata/invalid-bool-value.yaml ./config/testdata/invalid-disabled-bool-value.yaml ./config/testdata/invalid-disabled-bool-value2.yaml ./config/testdata/invalid-exporter-section.yaml ./config/testdata/invalid-extension-disabled-value.yaml ./config/testdata/invalid-extension-name.yaml ./config/testdata/invalid-extension-section.yaml ./config/testdata/invalid-pipeline-section.yaml ./config/testdata/invalid-pipeline-type-and-name.yaml ./config/testdata/invalid-pipeline-type.yaml ./config/testdata/invalid-processor-section.yaml ./config/testdata/invalid-receiver-name.yaml ./config/testdata/invalid-receiver-reference.yaml ./config/testdata/invalid-receiver-section.yaml ./config/testdata/invalid-sequence-value.yaml ./config/testdata/invalid-service-extensions-value.yaml ./config/testdata/invalid-service-section.yaml ./config/testdata/invalid-top-level-section.yaml ./config/testdata/metric-pipeline-cannot-have-processors.yaml ./config/testdata/missing-all-sections.yaml ./config/testdata/missing-enabled-exporters.yaml ./config/testdata/missing-enabled-receivers.yaml ./config/testdata/missing-exporter-name-after-slash.yaml ./config/testdata/missing-exporters.yaml ./config/testdata/missing-extension-type.yaml ./config/testdata/missing-pipelines.yaml ./config/testdata/missing-processor-type.yaml ./config/testdata/missing-processors.yaml ./config/testdata/missing-receiver-type.yaml ./config/testdata/missing-receivers.yaml ./config/testdata/multiproto-config.yaml ./config/testdata/pipeline-exporter-not-exists.yaml ./config/testdata/pipeline-must-have-exporter.yaml ./config/testdata/pipeline-must-have-exporter2.yaml ./config/testdata/pipeline-must-have-processors.yaml ./config/testdata/pipeline-must-have-receiver.yaml ./config/testdata/pipeline-processor-not-exists.yaml ./config/testdata/simple-config-with-all-env.yaml ./config/testdata/simple-config-with-no-env.yaml ./config/testdata/simple-config-with-partial-env.yaml ./config/testdata/unknown-exporter-type.yaml ./config/testdata/unknown-extension-type.yaml ./config/testdata/unknown-processor-type.yaml ./config/testdata/unknown-receiver-type.yaml ./config/testdata/valid-config.yaml ./docs/design.md ./docs/migrating-from-opencensus.md ./docs/monitoring.md ./docs/observability.md ./docs/performance.md ./docs/pipelines.md ./docs/roadmap.md ./docs/service-extensions.md ./docs/troubleshooting.md ./examples/demo/README.md ./examples/demo/docker-compose.yaml ./examples/demo/otel-agent-config.yaml ./examples/demo/otel-collector-config.yaml ./examples/demo/prometheus.yaml ./examples/k8s.yaml ./examples/otel-local-config.yaml ./exporter/README.md ./exporter/fileexporter/testdata/config.yaml ./exporter/jaeger/jaegergrpcexporter/testdata/config.yaml ./exporter/jaeger/jaegerthrifthttpexporter/testdata/config.yaml ./exporter/loggingexporter/testdata/config.yaml ./exporter/opencensusexporter/testdata/config.yaml ./exporter/otlpexporter/testdata/config.yaml ./exporter/prometheusexporter/testdata/config.yaml ./exporter/zipkinexporter/testdata/config.yaml ./extension/README.md ./extension/healthcheckextension/testdata/config.yaml ./extension/pprofextension/testdata/config.yaml ./extension/zpagesextension/testdata/config.yaml ./processor/README.md ./processor/attributesprocessor/testdata/config.yaml ./processor/batchprocessor/testdata/config.yaml ./processor/memorylimiter/testdata/config.yaml ./processor/queuedprocessor/testdata/config.yaml ./processor/resourceprocessor/testdata/config.yaml ./processor/samplingprocessor/probabilisticsamplerprocessor/testdata/config.yaml ./processor/samplingprocessor/probabilisticsamplerprocessor/testdata/empty.yaml ./processor/samplingprocessor/tailsamplingprocessor/testdata/tail_sampling_config.yaml ./processor/spanprocessor/testdata/config.yaml ./pull_request_template.md ./receiver/README.md ./receiver/jaegerreceiver/testdata/bad_empty_config.yaml ./receiver/jaegerreceiver/testdata/bad_no_proto_config.yaml ./receiver/jaegerreceiver/testdata/bad_proto_config.yaml ./receiver/jaegerreceiver/testdata/config.yaml ./receiver/opencensusreceiver/testdata/config.yaml ./receiver/otlpreceiver/testdata/config.yaml ./receiver/prometheusreceiver/README.md ./receiver/prometheusreceiver/testdata/config.yaml ./receiver/prometheusreceiver/testdata/config_env.yaml ./receiver/prometheusreceiver/testdata/invalid-config-section.yaml ./receiver/vmmetricsreceiver/example_config.yaml ./receiver/vmmetricsreceiver/testdata/config.yaml ./receiver/zipkinreceiver/testdata/config.yaml ./service/builder/testdata/bad_processor_factory.yaml ./service/builder/testdata/bad_receiver_factory.yaml ./service/builder/testdata/new_style_receiver_factory.yaml ./service/builder/testdata/pipelines_builder.yaml ./service/builder/testdata/unused_receiver.yaml ./service/testdata/otelcol-config.yaml ./testbed/README.md ./testbed/tests/local.yaml ./testbed/tests/results/BASELINE.md ./testbed/tests/results/TESTRESULTS.md ./testbed/tests/testdata/add-attributes-config.yaml ./testbed/tests/testdata/agent-config.yaml ./testbed/tests/testdata/memory-limiter.yaml ./translator/trace/README.md
go test -race -timeout 30s github.com/open-telemetry/opentelemetry-collector/client github.com/open-telemetry/opentelemetry-collector/cmd/otelcol github.com/open-telemetry/opentelemetry-collector/component github.com/open-telemetry/opentelemetry-collector/compression github.com/open-telemetry/opentelemetry-collector/compression/grpc github.com/open-telemetry/opentelemetry-collector/config github.com/open-telemetry/opentelemetry-collector/config/configcheck github.com/open-telemetry/opentelemetry-collector/config/configerror github.com/open-telemetry/opentelemetry-collector/config/configgrpc github.com/open-telemetry/opentelemetry-collector/config/configmodels github.com/open-telemetry/opentelemetry-collector/consumer github.com/open-telemetry/opentelemetry-collector/consumer/consumerdata github.com/open-telemetry/opentelemetry-collector/consumer/consumererror github.com/open-telemetry/opentelemetry-collector/defaults github.com/open-telemetry/opentelemetry-collector/examples github.com/open-telemetry/opentelemetry-collector/exporter github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper github.com/open-telemetry/opentelemetry-collector/exporter/exportertest github.com/open-telemetry/opentelemetry-collector/exporter/fileexporter github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegergrpcexporter github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegerthrifthttpexporter github.com/open-telemetry/opentelemetry-collector/exporter/loggingexporter github.com/open-telemetry/opentelemetry-collector/exporter/opencensusexporter github.com/open-telemetry/opentelemetry-collector/exporter/otlpexporter github.com/open-telemetry/opentelemetry-collector/exporter/prometheusexporter github.com/open-telemetry/opentelemetry-collector/exporter/zipkinexporter github.com/open-telemetry/opentelemetry-collector/extension/extensiontest github.com/open-telemetry/opentelemetry-collector/extension/healthcheckextension github.com/open-telemetry/opentelemetry-collector/extension/pprofextension github.com/open-telemetry/opentelemetry-collector/extension/zpagesextension github.com/open-telemetry/opentelemetry-collector/internal github.com/open-telemetry/opentelemetry-collector/internal/collector/telemetry github.com/open-telemetry/opentelemetry-collector/internal/data github.com/open-telemetry/opentelemetry-collector/internal/data_generator github.com/open-telemetry/opentelemetry-collector/internal/data_generator/internal github.com/open-telemetry/opentelemetry-collector/internal/processor github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset/regexp github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset/strict github.com/open-telemetry/opentelemetry-collector/internal/processor/span github.com/open-telemetry/opentelemetry-collector/internal/version github.com/open-telemetry/opentelemetry-collector/observability github.com/open-telemetry/opentelemetry-collector/observability/observabilitytest github.com/open-telemetry/opentelemetry-collector/obsreport github.com/open-telemetry/opentelemetry-collector/oterr github.com/open-telemetry/opentelemetry-collector/processor github.com/open-telemetry/opentelemetry-collector/processor/attributesprocessor github.com/open-telemetry/opentelemetry-collector/processor/batchprocessor github.com/open-telemetry/opentelemetry-collector/processor/memorylimiter github.com/open-telemetry/opentelemetry-collector/processor/processortest github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor github.com/open-telemetry/opentelemetry-collector/processor/resourceprocessor github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/probabilisticsamplerprocessor github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor/idbatcher github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor/sampling github.com/open-telemetry/opentelemetry-collector/processor/spanprocessor github.com/open-telemetry/opentelemetry-collector/receiver github.com/open-telemetry/opentelemetry-collector/receiver/jaegerreceiver github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver/metrics github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver/trace github.com/open-telemetry/opentelemetry-collector/receiver/prometheusreceiver github.com/open-telemetry/opentelemetry-collector/receiver/prometheusreceiver/internal github.com/open-telemetry/opentelemetry-collector/receiver/receivertest github.com/open-telemetry/opentelemetry-collector/receiver/vmmetricsreceiver github.com/open-telemetry/opentelemetry-collector/receiver/zipkinreceiver github.com/open-telemetry/opentelemetry-collector/service github.com/open-telemetry/opentelemetry-collector/service/builder github.com/open-telemetry/opentelemetry-collector/testutils github.com/open-telemetry/opentelemetry-collector/testutils/metricstestutils github.com/open-telemetry/opentelemetry-collector/translator/common github.com/open-telemetry/opentelemetry-collector/translator/conventions github.com/open-telemetry/opentelemetry-collector/translator/internaldata github.com/open-telemetry/opentelemetry-collector/translator/metrics github.com/open-telemetry/opentelemetry-collector/translator/opencensus github.com/open-telemetry/opentelemetry-collector/translator/trace github.com/open-telemetry/opentelemetry-collector/translator/trace/jaeger github.com/open-telemetry/opentelemetry-collector/translator/trace/spandata github.com/open-telemetry/opentelemetry-collector/translator/trace/zipkin
ok  	github.com/open-telemetry/opentelemetry-collector/client	1.439s
?   	github.com/open-telemetry/opentelemetry-collector/cmd/otelcol	[no test files]
ok  	github.com/open-telemetry/opentelemetry-collector/component	1.639s
ok  	github.com/open-telemetry/opentelemetry-collector/compression	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/compression/grpc	(cached)
ok  	github.com/open-telemetry/opentelemetry-collector/config	0.855s
ok  	github.com/open-telemetry/opentelemetry-collector/config/configcheck	2.172s
ok  	github.com/open-telemetry/opentelemetry-collector/config/configerror	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/config/configgrpc	1.890s
ok  	github.com/open-telemetry/opentelemetry-collector/config/configmodels	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/consumer	1.319s [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/consumer/consumerdata	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/consumer/consumererror	1.749s
ok  	github.com/open-telemetry/opentelemetry-collector/defaults	2.131s
?   	github.com/open-telemetry/opentelemetry-collector/examples	[no test files]
ok  	github.com/open-telemetry/opentelemetry-collector/exporter	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper	1.656s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/exportertest	1.555s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/fileexporter	1.418s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegergrpcexporter	2.517s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegerthrifthttpexporter	1.636s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/loggingexporter	1.571s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/opencensusexporter	1.883s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/otlpexporter	1.669s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/prometheusexporter	1.811s
ok  	github.com/open-telemetry/opentelemetry-collector/exporter/zipkinexporter	1.798s
ok  	github.com/open-telemetry/opentelemetry-collector/extension/extensiontest	1.473s
ok  	github.com/open-telemetry/opentelemetry-collector/extension/healthcheckextension	2.124s
ok  	github.com/open-telemetry/opentelemetry-collector/extension/pprofextension	2.299s
ok  	github.com/open-telemetry/opentelemetry-collector/extension/zpagesextension	1.790s
ok  	github.com/open-telemetry/opentelemetry-collector/internal	0.584s
ok  	github.com/open-telemetry/opentelemetry-collector/internal/collector/telemetry	(cached) [no tests to run]
panic: test timed out after 30s

goroutine 66 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1460 +0x11c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001566c0, 0x16b38c8, 0x18, 0x16c85e0, 0x1)
	/usr/local/go/src/testing/testing.go:1044 +0x699
testing.runTests.func1(0xc0001566c0)
	/usr/local/go/src/testing/testing.go:1285 +0xa7
testing.tRunner(0xc0001566c0, 0xc000191d50)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
testing.runTests(0xc00013e4e0, 0x1ac04c0, 0x2b, 0x2b, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x528
testing.(*M).Run(0xc000188080, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x300
main.main()
	_testmain.go:138 +0x224

goroutine 53 [runnable]:
reflect.Value.Field(0x167ab40, 0xc009ecd2a0, 0x1b9, 0x0, 0x16188c0, 0xc000ba1ca0, 0x1ab)
	/usr/local/go/src/reflect/value.go:825 +0x338
reflect.deepValueEqual(0x167ab40, 0xc000ba1ca0, 0x1b9, 0x167ab40, 0xc009ecd2a0, 0x1b9, 0xc005fafa58, 0xe, 0x0)
	/usr/local/go/src/reflect/deepequal.go:103 +0xdcd
reflect.deepValueEqual(0x16822c0, 0xc000b9c9d0, 0x1b6, 0x16822c0, 0xc009eb1ca0, 0x1b6, 0xc005fafa58, 0xd, 0xc009e70b01)
	/usr/local/go/src/reflect/deepequal.go:100 +0x1b23
reflect.deepValueEqual(0x160da80, 0xc000b65dd0, 0x1b7, 0x160da80, 0xc009e70bd0, 0x1b7, 0xc005fafa58, 0xc, 0x1)
	/usr/local/go/src/reflect/deepequal.go:86 +0x10ff
reflect.deepValueEqual(0x168f3e0, 0xc000b65d98, 0x1b9, 0x168f3e0, 0xc009e70b98, 0x1b9, 0xc005fafa58, 0xb, 0x0)
	/usr/local/go/src/reflect/deepequal.go:103 +0xe34
reflect.deepValueEqual(0x168e360, 0xc000b9c7f8, 0x1b6, 0x168e360, 0xc009eb1ac8, 0x1b6, 0xc005fafa58, 0xa, 0xc009df1a01)
	/usr/local/go/src/reflect/deepequal.go:100 +0x1b23
reflect.deepValueEqual(0x160da40, 0xc000ae2d10, 0x1b7, 0x160da40, 0xc009df1b10, 0x1b7, 0xc005fafa58, 0x9, 0x1)
	/usr/local/go/src/reflect/deepequal.go:86 +0x10ff
reflect.deepValueEqual(0x1687620, 0xc000ae2cd8, 0x1b9, 0x1687620, 0xc009df1ad8, 0x1b9, 0xc005fafa58, 0x8, 0x0)
	/usr/local/go/src/reflect/deepequal.go:103 +0xe34
reflect.deepValueEqual(0x1688bc0, 0xc000ae10f8, 0x1b6, 0x1688bc0, 0xc009e1c3d8, 0x1b6, 0xc005fafa58, 0x7, 0xc0000b3001)
	/usr/local/go/src/reflect/deepequal.go:100 +0x1b23
reflect.deepValueEqual(0x160db40, 0xc0000b2608, 0x1b7, 0x160db40, 0xc0000b3088, 0x1b7, 0xc005fafa58, 0x6, 0x1)
	/usr/local/go/src/reflect/deepequal.go:86 +0x10ff
reflect.deepValueEqual(0x167ac20, 0xc0000b2600, 0x1b9, 0x167ac20, 0xc0000b3080, 0x1b9, 0xc005fafa58, 0x5, 0x0)
	/usr/local/go/src/reflect/deepequal.go:103 +0xe34
reflect.deepValueEqual(0x16823c0, 0xc0000b40c0, 0x1b6, 0x16823c0, 0xc005ef9860, 0x1b6, 0xc005fafa58, 0x4, 0xc0000b2201)
	/usr/local/go/src/reflect/deepequal.go:100 +0x1b23
reflect.deepValueEqual(0x160dac0, 0xc0000a4208, 0x1b7, 0x160dac0, 0xc0000b2248, 0x1b7, 0xc005fafa58, 0x3, 0x1)
	/usr/local/go/src/reflect/deepequal.go:86 +0x10ff
reflect.deepValueEqual(0x167ad00, 0xc0000a4200, 0x1b9, 0x167ad00, 0xc0000b2240, 0x1b9, 0xc005fafa58, 0x2, 0xc0000b2240)
	/usr/local/go/src/reflect/deepequal.go:103 +0xe34
reflect.deepValueEqual(0x16824c0, 0xc0000a4200, 0x36, 0x16824c0, 0xc0000b2240, 0x36, 0xc0000ada58, 0x1, 0xc0000ad8b0)
	/usr/local/go/src/reflect/deepequal.go:100 +0x1b23
reflect.deepValueEqual(0x1671be0, 0xc0000a4200, 0x19, 0x1671be0, 0xc0000b2240, 0x19, 0xc005fafa58, 0x0, 0x158416b)
	/usr/local/go/src/reflect/deepequal.go:103 +0xe34
reflect.DeepEqual(0x1671be0, 0xc0000a4200, 0x1671be0, 0xc0000b2240, 0xc0000adc10)
	/usr/local/go/src/reflect/deepequal.go:198 +0x33a
github.com/stretchr/testify/assert.ObjectsAreEqual(0x1671be0, 0xc0000a4200, 0x1671be0, 0xc0000b2240, 0x8)
	/Users/tnajaryan/go/pkg/mod/github.com/stretchr/testify@v1.4.0/assert/assertions.go:64 +0x23c
github.com/stretchr/testify/assert.ObjectsAreEqualValues(0x1671be0, 0xc0000a4200, 0x1671be0, 0xc0000b2240, 0xc000096360)
	/Users/tnajaryan/go/pkg/mod/github.com/stretchr/testify@v1.4.0/assert/assertions.go:80 +0x78
github.com/stretchr/testify/assert.EqualValues(0x1763ae0, 0xc000096360, 0x1671be0, 0xc0000a4200, 0x1671be0, 0xc0000b2240, 0x0, 0x0, 0x0, 0x1094b01)
	/Users/tnajaryan/go/pkg/mod/github.com/stretchr/testify@v1.4.0/assert/assertions.go:410 +0xb7
github.com/open-telemetry/opentelemetry-collector/internal/data.TestResourceMetricsSlice(0xc000096360)
	/Users/tnajaryan/work/repos/opentelemetry-collector/internal/data/generated_metrics_test.go:39 +0x305
testing.tRunner(0xc000096360, 0x16c85e0)
	/usr/local/go/src/testing/testing.go:992 +0x1ec
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x661
FAIL	github.com/open-telemetry/opentelemetry-collector/internal/data	31.487s
?   	github.com/open-telemetry/opentelemetry-collector/internal/data_generator	[no test files]
?   	github.com/open-telemetry/opentelemetry-collector/internal/data_generator/internal	[no test files]
ok  	github.com/open-telemetry/opentelemetry-collector/internal/processor	1.448s
ok  	github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset/regexp	1.368s
ok  	github.com/open-telemetry/opentelemetry-collector/internal/processor/filterset/strict	1.360s
ok  	github.com/open-telemetry/opentelemetry-collector/internal/processor/span	1.854s
ok  	github.com/open-telemetry/opentelemetry-collector/internal/version	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/observability	1.851s
ok  	github.com/open-telemetry/opentelemetry-collector/observability/observabilitytest	0.754s
ok  	github.com/open-telemetry/opentelemetry-collector/obsreport	1.532s
ok  	github.com/open-telemetry/opentelemetry-collector/oterr	(cached)
ok  	github.com/open-telemetry/opentelemetry-collector/processor	1.460s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/attributesprocessor	1.706s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/batchprocessor	8.705s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/memorylimiter	1.617s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/processortest	1.588s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor	0.915s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/resourceprocessor	2.777s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/probabilisticsamplerprocessor	18.915s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor	6.247s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor/idbatcher	3.758s
ok  	github.com/open-telemetry/opentelemetry-collector/processor/samplingprocessor/tailsamplingprocessor/sampling	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/processor/spanprocessor	1.709s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver	1.643s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/jaegerreceiver	3.833s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver	1.702s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics	1.580s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/octrace	2.334s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver	0.883s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver/metrics	0.695s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/otlpreceiver/trace	1.529s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/prometheusreceiver	21.644s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/prometheusreceiver/internal	1.714s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/receivertest	1.340s [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/vmmetricsreceiver	1.471s
ok  	github.com/open-telemetry/opentelemetry-collector/receiver/zipkinreceiver	0.907s
ok  	github.com/open-telemetry/opentelemetry-collector/service	2.034s
ok  	github.com/open-telemetry/opentelemetry-collector/service/builder	1.604s
ok  	github.com/open-telemetry/opentelemetry-collector/testutils	5.944s
ok  	github.com/open-telemetry/opentelemetry-collector/testutils/metricstestutils	2.325s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/common	1.319s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/conventions	(cached) [no tests to run]
ok  	github.com/open-telemetry/opentelemetry-collector/translator/internaldata	2.336s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/metrics	1.365s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/opencensus	1.416s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/trace	1.681s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/trace/jaeger	1.700s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/trace/spandata	1.394s
ok  	github.com/open-telemetry/opentelemetry-collector/translator/trace/zipkin	1.785s
FAIL
make: *** [test] Error 1

Process finished with exit code 2
```

**Comment by bogdandrutu** [comment]
Obsolete, please reopen if you see this again.
