### ISSUE TITLE
docker compose demo is broken

### ISSUE THREAD

**Issue by rueian** [open-telemetry/opentelemetry-collector#846]
Hi, I notice that the `otel-agent` will go panic after receiving metrics from the demo metrics-load-generator (https://github.com/open-telemetry/opentelemetry-collector/blob/5e3b4e2cee14e1df8fafbe36776cd2f8a7445ac4/examples/main.go).

Steps to reproduce:
1. start the demo

```
$ git clone git@github.com:open-telemetry/opentelemetry-collector.git; \
    cd examples/demo; \
    docker-compose up -d
```

2. watch the logs of otel-agent

```
$ docker-compose logs -f otel-agent
```

Here is the logs:

```
...
otel-agent_1              | Span #2
otel-agent_1              |     Trace ID       : 000000000000000029ac27b20fe63608
otel-agent_1              |     Parent ID      : 29ac27b20fe63608
otel-agent_1              |     ID             : 09086d91c950909f
otel-agent_1              |     Name           : /getrecommendations
otel-agent_1              |     Kind           : SPAN_KIND_UNSPECIFIED
otel-agent_1              |     Start time     : 2020-04-19 17:49:27.798 +0000 UTC
otel-agent_1              |     End time       : 2020-04-19 17:49:28.012 +0000 UTC
otel-agent_1              | Attributes:
otel-agent_1              |      -> http.url: STRING(http://recommendationservice/GetRecommendations)
otel-agent_1              |      -> instance: STRING(recommendationservice-d847fdcf5-j6s2f)
otel-agent_1              |      -> region: STRING(us-east-1)
otel-agent_1              |      -> version: STRING(v234)
otel-agent_1              |      -> ipv4: STRING(172.21.0.8)
otel-agent_1              |      -> http.method: STRING(GET)
otel-agent_1              | Span #3
otel-agent_1              |     Trace ID       : 0000000000000000b68a81046f1cec70
otel-agent_1              |     Parent ID      : b68a81046f1cec70
otel-agent_1              |     ID             : 6d393617159f532e
otel-agent_1              |     Name           : /getrecommendations
otel-agent_1              |     Kind           : SPAN_KIND_UNSPECIFIED
otel-agent_1              |     Start time     : 2020-04-19 17:49:27.967 +0000 UTC
otel-agent_1              |     End time       : 2020-04-19 17:49:28.257 +0000 UTC
otel-agent_1              | Attributes:
otel-agent_1              |      -> ipv4: STRING(172.21.0.8)
otel-agent_1              |      -> version: STRING(v234)
otel-agent_1              |      -> http.method: STRING(GET)
otel-agent_1              |      -> http.url: STRING(http://recommendationservice/GetRecommendations)
otel-agent_1              |      -> instance: STRING(recommendationservice-6b654dbf57-zq8dt)
otel-agent_1              |      -> region: STRING(us-east-1)
otel-agent_1              |
otel-agent_1              | 2020-04-19T17:49:28.353Z	INFO	loggingexporter/logging_exporter.go:157	MetricsExporter	{"#metrics": 4}
otel-agent_1              | panic: Unsupported metrics type.
otel-agent_1              |
otel-agent_1              | goroutine 693 [running]:
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/consumer/pdatautil.MetricAndDataPointCount(0x1ea2be0, 0xc000d9cda0, 0x1ea2be0, 0xc000d9cda0)
otel-agent_1              | 	/home/circleci/project/consumer/pdatautil/pdatautil.go:114 +0x149
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.pushMetricsWithObservability.func1(0x286f840, 0xc00046f350, 0x1ea2be0, 0xc000d9cda0, 0x286f840, 0xc00046f1d0, 0x1efa3e0)
otel-agent_1              | 	/home/circleci/project/exporter/exporterhelper/metricshelper.go:166 +0xd4
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.(*metricsExporter).ConsumeMetrics(0xc000386340, 0x286f840, 0xc00046f110, 0x1ea2be0, 0xc000d9cda0, 0x1fa7a80, 0xc000b419a0)
otel-agent_1              | 	/home/circleci/project/exporter/exporterhelper/metricshelper.go:121 +0x84
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/processor.metricsFanOutConnector.ConsumeMetrics(0xc0003730c0, 0x2, 0x2, 0x286f840, 0xc00046f110, 0x1ea2be0, 0xc000d9cda0, 0xc00046f001, 0xc000d9cda0)
otel-agent_1              | 	/home/circleci/project/processor/fanoutconnector.go:87 +0xba
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/consumer/converter.(*ocToInternalMetricsConverter).ConsumeMetricsData(0xc0004f6000, 0x286f840, 0xc00046f110, 0xc00095cac0, 0xc000c80940, 0xc000d9cce0, 0x4, 0x4, 0xc000b1baf0, 0x1)
otel-agent_1              | 	/home/circleci/project/consumer/converter/converter.go:122 +0xbb
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.(*Receiver).sendToNextConsumer(0xc0004ae220, 0x286f840, 0xc000dabcb0, 0xc00095cac0, 0xc000c80940, 0xc000d9cce0, 0x4, 0x4, 0xcc93a2, 0xc000978840)
otel-agent_1              | 	/home/circleci/project/receiver/opencensusreceiver/ocmetrics/opencensus.go:148 +0x210
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.(*Receiver).processReceivedMsg(0xc0004ae220, 0x286f840, 0xc000dabcb0, 0xc00095cac0, 0xc000c80940, 0xc0002481e0, 0xc00095cac0, 0xc00095cb80, 0x0, 0x0)
otel-agent_1              | 	/home/circleci/project/receiver/opencensusreceiver/ocmetrics/opencensus.go:125 +0xe2
otel-agent_1              | github.com/open-telemetry/opentelemetry-collector/receiver/opencensusreceiver/ocmetrics.(*Receiver).Export(0xc0004ae220, 0x288ac40, 0xc000bc9880, 0x281fe20, 0xc0004ae220)
otel-agent_1              | 	/home/circleci/project/receiver/opencensusreceiver/ocmetrics/opencensus.go:81 +0x138
otel-agent_1              | github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1._MetricsService_Export_Handler(0x20bc4e0, 0xc0004ae220, 0x2883860, 0xc000978840, 0x3ab4b60, 0xc000944800)
otel-agent_1              | 	/home/circleci/go/pkg/mod/github.com/census-instrumentation/opencensus-proto@v0.2.1/gen-go/agent/metrics/v1/metrics_service.pb.go:237 +0xad
otel-agent_1              | google.golang.org/grpc.(*Server).processStreamingRPC(0xc0001724e0, 0x288ff80, 0xc0005f7200, 0xc000944800, 0xc0004a0630, 0x3a63c00, 0x0, 0x0, 0x0)
otel-agent_1              | 	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:1329 +0xcdd
otel-agent_1              | google.golang.org/grpc.(*Server).handleStream(0xc0001724e0, 0x288ff80, 0xc0005f7200, 0xc000944800, 0x0)
otel-agent_1              | 	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:1409 +0xc62
otel-agent_1              | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000c9fd90, 0xc0001724e0, 0x288ff80, 0xc0005f7200, 0xc000944800)
otel-agent_1              | 	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:746 +0xa1
otel-agent_1              | created by google.golang.org/grpc.(*Server).serveStreams.func1
otel-agent_1              | 	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.28.1/server.go:744 +0xa1
demo_otel-agent_1 exited with code 2
```

**Comment by bogdandrutu** [comment]
Fixed in #883
