### ISSUE TITLE
Component Status Reporting feature broke the contrib build

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#8645]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1709f71]

goroutine 6 [running]:
go.opentelemetry.io/collector/internal/sharedcomponent.(*SharedComponent[...]).Start.func1()
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.86.1-0.20231006183[53](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:54)8-53615832e6[54](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:55)/internal/sharedcomponent/sharedcomponent.go:92 +0x191
sync.(*Once).doSlow(0xc0000ff708, 0xc000753330)
	/opt/hostedtoolcache/go/1.20.8/x64/src/sync/once.go:74 +0x102
sync.(*Once).Do(0xc0000ff708, 0xc000926fc0?)
	/opt/hostedtoolcache/go/1.20.8/x64/src/sync/once.go:65 +0x47
go.opentelemetry.io/collector/internal/sharedcomponent.(*SharedComponent[...]).Start(0x67ac680, {0x67bf2e8, 0xc000134008}, {0x67c0158, 0xc000926a10})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.86.1-0.20231006183538-53615832e654/internal/sharedcomponent/sharedcomponent.go:87 +0xe5
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll(0xc000378fd0, {0x67bf2e8, 0xc000134008}, {0x67c0158, 0xc000926a10})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/service@v0.86.1-0.20231006161201-d364ad61c4d7/internal/graph/graph.go:334 +0x113
go.opentelemetry.io/collector/service.(*Service).Start(0xc00067a0a0, {0x67bf2e8, 0xc000134008})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/service@v0.86.1-0.20231006161201-d364ad61c4d7/service.go:153 +0x[56](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:57)f
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000334900, {0x67bf2e8, 0xc000134008})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/otelcol@v0.86.1-0.2023100[61](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:62)61201-d3[64](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:65)ad61c4d7/collector.go:186 +0xbf7
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000334900, {0x[67](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:68)bf2e8, 0xc000134008})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/otelcol@v0.86.1-0.20231006161201-d364ad61c4d7/collector.go:221 +0x74
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*inProcessCollector).Start.func1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed/testbed/in_process_collector.go:87 +0xc7
created by github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*inProcessCollector).Start
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed/testbed/in_process_collector.go:85 +0x5f2
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/correctnesstests/metrics	0.190s
?   	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/datareceivers	[no test files]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/datasenders	[no test files]
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/correctnesstests/traces	0.1[70](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602#step:9:71)s
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/stabilitytests	0.180s
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6474057287/job/17578309136?pr=27602

**Comment by codeboten** [comment]
pinging @mwear about this

**Comment by dmitryax** [comment]
Sorry, false alarm. Appeared to be the incomplete core dependency update :)
