### ISSUE TITLE
Panic with jaeger http exporter

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-collector#880]
I'm seeing the following panic running the collector v0.3.0 on a k8s cluster with the jaeger_thrift_http exporter configured. I'm using the otlp trace library to export my spans, receiving them with the otlp receiver in the collector, but this error arises trying to export to jaeger_thrift_http:

```
$ oc logs pod/opentelemetry-collector-5697c57b99-fkwmd
{"level":"info","ts":1588023749.387314,"caller":"service/service.go:418","msg":"Starting OpenTelemetry Collector...","Version":"latest","GitHash":"b4512e7","NumCPU":4}
{"level":"info","ts":1588023749.387366,"caller":"service/service.go:193","msg":"Setting up own telemetry..."}
{"level":"info","ts":1588023749.3877065,"caller":"service/telemetry.go:147","msg":"Serving Prometheus metrics","port":8888,"legacy_metrics":true,"new_metrics":false,"level":0,"service.instance.id":""}
{"level":"info","ts":1588023749.387737,"caller":"service/service.go:227","msg":"Loading configuration..."}
{"level":"info","ts":1588023749.3887825,"caller":"service/service.go:238","msg":"Applying configuration..."}
{"level":"info","ts":1588023749.3888288,"caller":"builder/exporters_builder.go:248","msg":"Exporter is enabled.","exporter":"jaeger_thrift_http"}
{"level":"info","ts":1588023749.3888984,"caller":"builder/exporters_builder.go:248","msg":"Exporter is enabled.","exporter":"logging"}
{"level":"info","ts":1588023749.3889086,"caller":"service/service.go:295","msg":"Starting exporters..."}
{"level":"info","ts":1588023749.3889155,"caller":"builder/exporters_builder.go:80","msg":"Exporter is starting...","exporter":"jaeger_thrift_http"}
{"level":"info","ts":1588023749.3889232,"caller":"builder/exporters_builder.go:85","msg":"Exporter started.","exporter":"jaeger_thrift_http"}
{"level":"info","ts":1588023749.3889298,"caller":"builder/exporters_builder.go:80","msg":"Exporter is starting...","exporter":"logging"}
{"level":"info","ts":1588023749.3889396,"caller":"builder/exporters_builder.go:85","msg":"Exporter started.","exporter":"logging"}
{"level":"info","ts":1588023749.388969,"caller":"builder/pipelines_builder.go:185","msg":"Pipeline is enabled.","pipelines":"traces"}
{"level":"info","ts":1588023749.3889787,"caller":"service/service.go:308","msg":"Starting processors..."}
{"level":"info","ts":1588023749.3889859,"caller":"builder/pipelines_builder.go:50","msg":"Pipeline is starting...","pipeline":"traces"}
{"level":"info","ts":1588023749.389402,"caller":"builder/pipelines_builder.go:60","msg":"Pipeline is started.","pipeline":"traces"}
{"level":"info","ts":1588023749.3894567,"caller":"builder/receivers_builder.go:219","msg":"Receiver is enabled.","receiver":"otlp","datatype":"traces"}
{"level":"info","ts":1588023749.38947,"caller":"service/service.go:320","msg":"Starting receivers..."}
{"level":"info","ts":1588023749.389483,"caller":"builder/receivers_builder.go:72","msg":"Receiver is starting...","receiver":"otlp"}
{"level":"info","ts":1588023749.3897092,"caller":"builder/receivers_builder.go:77","msg":"Receiver started.","receiver":"otlp"}
{"level":"info","ts":1588023749.3897207,"caller":"service/service.go:205","msg":"Everything is ready. Begin running and processing data."}
2020-04-27T21:42:44.742Z	INFO	loggingexporter/logging_exporter.go:104	TraceData with 1 spans, resource "" (0 labels)
	{"exporter": "logging"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbd0ec9]

goroutine 103 [running]:
github.com/jaegertracing/jaeger/thrift-gen/jaeger.(*Process).writeField1(0x0, 0x28c5300, 0xc0001d2510, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/thrift-gen/jaeger/ttypes.go:1540 +0x89
github.com/jaegertracing/jaeger/thrift-gen/jaeger.(*Process).Write(0x0, 0x28c5300, 0xc0001d2510, 0x1980c, 0x0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/thrift-gen/jaeger/ttypes.go:1521 +0x82
github.com/jaegertracing/jaeger/thrift-gen/jaeger.(*Batch).writeField1(0xc000235b30, 0x28c5300, 0xc0001d2510, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/thrift-gen/jaeger/ttypes.go:1944 +0xa0
github.com/jaegertracing/jaeger/thrift-gen/jaeger.(*Batch).Write(0xc000235b30, 0x28c5300, 0xc0001d2510, 0x7f89f267e150, 0xc0005760d0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/thrift-gen/jaeger/ttypes.go:1919 +0x82
github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegerthrifthttpexporter.serializeThrift(0x284b7a0, 0xc000235b30, 0xc000402140, 0x1, 0x1)
	/home/circleci/project/exporter/jaeger/jaegerthrifthttpexporter/exporter.go:128 +0x1a3
github.com/open-telemetry/opentelemetry-collector/exporter/jaeger/jaegerthrifthttpexporter.(*jaegerThriftHTTPSender).pushTraceData(0xc00000db40, 0x2883860, 0xc000235ad0, 0xc0000c29c0, 0xc0000c2a00, 0xc000402140, 0x1, 0x1, 0x2437232, 0xa, ...)
	/home/circleci/project/exporter/jaeger/jaegerthrifthttpexporter/exporter.go:89 +0x97
github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.traceDataPusherOld.withObservability.func1(0x2883860, 0xc000235ad0, 0xc0000c29c0, 0xc0000c2a00, 0xc000402140, 0x1, 0x1, 0x2437232, 0xa, 0x0, ...)
	/home/circleci/project/exporter/exporterhelper/tracehelper.go:98 +0xc9
github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.(*traceExporterOld).ConsumeTraceData(0xc00000db80, 0x2883860, 0xc00055bc20, 0xc0000c29c0, 0xc0000c2a00, 0xc000402140, 0x1, 0x1, 0x2437232, 0xa, ...)
	/home/circleci/project/exporter/exporterhelper/tracehelper.go:48 +0xa7
github.com/open-telemetry/opentelemetry-collector/processor.traceFanOutConnectorOld.ConsumeTraceData(0xc00000dd40, 0x2, 0x2, 0x2883860, 0xc00055bc20, 0xc0000c29c0, 0xc0000c2a00, 0xc000402140, 0x1, 0x1, ...)
	/home/circleci/project/processor/fanoutconnector.go:130 +0xeb
github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor.(*queuedSpanProcessor).processItemFromQueue(0xc0003ff6e0, 0xc0004072c0)
	/home/circleci/project/processor/queuedprocessor/queued_processor.go:159 +0xf8
github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor.(*queuedSpanProcessor).Start.func1(0x1e6f5c0, 0xc0004072c0)
	/home/circleci/project/processor/queuedprocessor/queued_processor.go:92 +0x45
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1(0xc00039ef70, 0xc000372aa0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/pkg/queue/bounded_queue.go:77 +0xb9
created by github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/pkg/queue/bounded_queue.go:68 +0xc0
```

I'm assuming it's from some inability to reach my jaeger endpoint, but a panic here is probably not the best for debugging this. My config is:

```
    receivers:
      otlp:
        endpoint: ":9090"

    processors:
      queued_retry:

    exporters:
      logging:
        loglevel: info
      jaeger_thrift_http:
        url: "http://jaeger-all-in-one-inmemory-collector.jaeger:14268/api/traces"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [queued_retry]
          exporters: [logging,jaeger_thrift_http]
```

And my jaeger service is up:
`service/jaeger-all-in-one-inmemory-collector            ClusterIP   172.30.234.178   <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   9m40s`

This wasn't occurring before, but I did delete the jaeger inmemory pod to get it to restart and it seems that the error has started happening after that. I wouldn't be surprised if this was my own fault, but maybe there could be an improvement to the error handling here to help diagnose that.

**Comment by damemi** [comment]
Update: On a fresh cluster I'm seeing this too, the error seems to come from https://github.com/jaegertracing/jaeger/blob/v1.17.0/thrift-gen/jaeger/ttypes.go#L1540

So it's possible that `p.ServiceName` is nil, is there a way to set that field with the otlp exporter?

**Comment by paulosman** [comment]
This appears to have been fixed in #165. Specifically with the reintroduction of the `OCProtoToJaegerThrift` translator, a span without `p.ServiceName` explicitly set will get a default value: `unknown-service-name`.

**Comment by damemi** [comment]
@paulosman is that the right PR (165?) 

Also, I was running this on the v0.3.0 image published to dockerhub, which I think was last updated a couple months ago. If the fix is already in master then I'm sorry for the irrelevant bug report!

**Comment by paulosman** [comment]
@damemi my mistake, I meant this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/165 . Sorry about that! 

Yeah, unfortunately that PR is newer than the docker image you're using. I don't suppose you'd be able to test against an image built from the contrib repository master?

**Comment by paulosman** [comment]
I was able to reproduce the bug and the fix. Using the v0.3.0 image, I get the same panic you're describing but if I use the master branch of the [opentelementry-collector-contrib repository](https://github.com/open-telemetry/opentelemetry-collector-contrib), it works as described earlier (the spans are given the service_name `unknown-service-name`). Please note also that the configuration directive has also changed from `jaeger_thrift_http` to `jaeger_thrift` in that version.

**Comment by damemi** [comment]
@paulosman thanks, I haven't given it a try yet for myself but I believe you.

Is it possible to configure the service name with the otlp api, so that I could use that in my code but ultimately export it to Jaeger from the collector without `unknown-service-name`?

**Comment by paulosman** [comment]
@damemi yeah, I agree that's the outstanding issue - let me take a look and I'll update here. If it's not possible, I'll see if I can put a proposal PR together.

**Comment by paulosman** [comment]
Looks like the service name issue is being discussed in #815 . Suggest closing this issue since the panic is no longer happening - solutions for populating Process tags are being discussed in #815. @damemi does that look right to you?

**Comment by damemi** [comment]
@paulosman thanks for the update, looks like that issue covers what I was talking about. Closing this in that case
