### ISSUE TITLE
Exporter failed send data to collector to https://otlp.nr-data.net:4317/ endpoint. Data will not be sent. Exception: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Failed to deserialize response message. The response header contains a gRPC status of OK, which means any message returned to the client for this call should be ignored. A unary or client streaming gRPC call must have a response message, which makes this response invalid.")

### ISSUE THREAD

**Issue by hunorczirjek** [open-telemetry/opentelemetry-collector#9770]
Hello, 

We are trying to fix an issue related to OpenTelemetry Exporter, we have multiple .net web applications ((Microsoft.NET.Sdk.Web) targeting .net 7.0 and .net 8.0) using opentelemetry and sending logs, traces and metrics to NewRelic.

Recently an error regarding OpenTelemetry Exporter started to be thrown:
2024-03-15 11:47:08 Error: OpenTelemetry-Exporter-OpenTelemetryProtocol - EventId: [2], EventName: [FailedToReachCollector]:
2024-03-15 11:47:08 Exporter failed send data to collector to https://otlp.nr-data.net:4317/ endpoint. Data will not be sent. Exception: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Failed to deserialize response message. The response header contains a gRPC status of OK, which means any message returned to the client for this call should be ignored. A unary or client streaming gRPC call must have a response message, which makes this response invalid.")
2024-03-15 11:47:08    at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
2024-03-15 11:47:08    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
2024-03-15 11:47:08    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
2024-03-15 11:47:08    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
2024-03-15 11:47:08    at OpenTelemetry.Proto.Collector.Trace.V1.TraceService.TraceServiceClient.Export(ExportTraceServiceRequest request, CallOptions options)
2024-03-15 11:47:08    at OpenTelemetry.Proto.Collector.Trace.V1.TraceService.TraceServiceClient.Export(ExportTraceServiceRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
2024-03-15 11:47:08    at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcTraceExportClient.SendExportRequest(ExportTraceServiceRequest request, CancellationToken cancellationToken)

Also happening for OpenTelemetry.Proto.Collector.Logs.V1.LogsService.LogsServiceClient.Export(ExportLogsServiceRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken).

We were able to debug the problem to some point, it looks like that the error is thrown when we try to export the following request in OtlpGrpcTraceExportClient.cs in SendExportRequest method:
"{{ "resourceSpans": [ { "resource": { "attributes": [ { "key": "host.name", "value": { "stringValue": "hostName" } }, { "key": "host.os.version", "value": { "stringValue": "Unix 5.15.146.1" } }, { "key": "service.name", "value": { "stringValue": "Service" } }, { "key": "service.namespace", "value": { "stringValue": "nameSpaceName" } }, { "key": "service.version", "value": { "stringValue": "1.0.0+69e374c0e12ee1661742b645bd00a1fe57620a04" } }, { "key": "service.instance.id", "value": { "stringValue": "xxxxx" } }, { "key": "telemetry.sdk.name", "value": { "stringValue": "opentelemetry" } }, { "key": "telemetry.sdk.language", "value": { "stringValue": "dotnet" } }, { "key": "telemetry.sdk.version", "value": { "stringValue": "1.7.0" } } ] }, "scopeSpans": [ { "scope": { "name": "MassTransit", "version": "8.1.3.0" }, "spans": [ { "traceId": "base64EncodedTraceId", "spanId": "base64EncodedSpanId", "name": "Configure Topology", "kind": "SPAN_KIND_CLIENT", "startTimeUnixNano": "1710495551381841000", "endTimeUnixNano": "1710495795667301400", "status": { "code": "STATUS_CODE_OK" } } ] } ] } ] }}"

We were not able to further debug the issue. We can not see/check the response.

We updated the OpenTelemetry nuget packages (to latest version (1.7.0)) and also tried using the latest version of otel/opentelemetry-collector docker image, but it did not fix the issue.

Can you please help us to solve this issue?

**Comment by edhjer** [comment]
https://github.com/grpc/grpc-dotnet/issues/1541#issuecomment-1001740004 and https://github.com/grpc/grpc-dotnet/pull/1931 seem to contain some info about the error message being logged here

Other things worth mentioning:
-  the payload shared above looks to be invalid JSON with the extra `{` and `}` (`...error getting request data: invalid character '{' looking for beginning of object key string` is what I get when trying to send with `grpcurl`)
- `traceId` and `spanId` need to be base64 encoded values (`...error getting request data: illegal base64 data at input byte 16`)
- fixing those two things at least gets me a successful response

> Recently an error regarding OpenTelemetry Exporter started to be thrown

Was this working previously with a different version? Around when did these errors start up? 

This also may get better eyes over in https://github.com/open-telemetry/opentelemetry-dotnet/tree/main cc @alanwest
